import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanExtraTaskCatalog {
  const GermanExtraTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-letter-sound-l',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe passt zum Laut?',
      prompt: 'lll',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['L'],
      choices: <String>['L', 'M', 'R'],
    ),
    GermanTask(
      id: 'g1-vowel-o',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe ist ein Selbstlaut?',
      prompt: 'Wähle den Selbstlaut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['O'],
      choices: <String>['K', 'O', 'N'],
    ),
    GermanTask(
      id: 'g1-alpha-bear-fish',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort kommt im Alphabet zuerst?',
      prompt: 'Fisch · Bär · Zebra',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Bär'],
      choices: <String>['Fisch', 'Bär', 'Zebra'],
    ),
    GermanTask(
      id: 'g1-syllables-tomate',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort hat drei Sprechsilben?',
      prompt: 'Sprich die Wörter langsam.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tomate'],
      choices: <String>['Tomate', 'Tisch', 'Hase'],
    ),
    GermanTask(
      id: 'g1-build-mouse',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'M · au · s',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Maus'],
      choices: <String>['Maus', 'Haus', 'Mund'],
    ),
    GermanTask(
      id: 'g1-build-house',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'H · au · s',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Haus'],
      choices: <String>['Haus', 'Maus', 'Hase'],
    ),
    GermanTask(
      id: 'g1-read-word-blume',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort steht hier?',
      prompt: 'Blume',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Blume'],
      choices: <String>['Blume', 'Baum', 'Brot'],
    ),
    GermanTask(
      id: 'g1-sentence-understand-cat',
      competencyId: GermanCompetencyId.sentenceComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Wo sitzt die Katze?',
      prompt: 'Die Katze sitzt auf dem Sofa.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['auf dem Sofa'],
      choices: <String>['auf dem Sofa', 'unter dem Tisch', 'im Garten'],
    ),
    GermanTask(
      id: 'g1-listen-dog',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör genau zu. Wo wartet der Hund?',
      prompt: 'Tippe auf Lautsprecher und wähle dann den Ort.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['vor der Tür'],
      choices: <String>['vor der Tür', 'im Bett', 'auf dem Baum'],
      spokenText: 'Der Hund wartet vor der Tür.',
    ),
    GermanTask(
      id: 'g1-order-child-laughs',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'laut · Das Kind · lacht',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Das Kind lacht laut'],
      choices: <String>['Das Kind', 'lacht', 'laut'],
    ),
    GermanTask(
      id: 'g2-noun-article-flower',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Artikel passt?',
      prompt: '___ Blume',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die'],
      choices: <String>['der', 'die', 'das'],
    ),
    GermanTask(
      id: 'g2-plural-child',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Wie lautet die Mehrzahl?',
      prompt: 'das Kind',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Kinder'],
      choices: <String>['die Kinder', 'die Häuser', 'die Mäuse'],
    ),
    GermanTask(
      id: 'g2-adjective-fast',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort beschreibt eine Eigenschaft?',
      prompt: 'Das schnelle Pferd läuft.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['schnelle'],
      choices: <String>['schnelle', 'Pferd', 'läuft'],
    ),
    GermanTask(
      id: 'g2-verb-jumps',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort sagt, was jemand tut?',
      prompt: 'Noah springt hoch.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['springt'],
      choices: <String>['Noah', 'springt', 'hoch'],
    ),
    GermanTask(
      id: 'g2-verb-inflect-go',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Form passt in den Satz?',
      prompt: 'Du ___ nach Hause. · Grundform: gehen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['gehst'],
      choices: <String>['gehe', 'gehst', 'geht'],
    ),
    GermanTask(
      id: 'g2-punctuation-statement',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Satzzeichen gehört ans Ende?',
      prompt: 'Heute scheint die Sonne',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['.'],
      choices: <String>['.', '?', '!'],
    ),
    GermanTask(
      id: 'g2-sentence-type-command',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Satzart ist das?',
      prompt: 'Mach bitte die Tür zu!',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Aufforderungssatz'],
      choices: <String>['Fragesatz', 'Aussagesatz', 'Aufforderungssatz'],
    ),
    GermanTask(
      id: 'g2-word-family-play',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort gehört zur Wortfamilie von „spielen“?',
      prompt: 'spielen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Spielplatz'],
      choices: <String>['Spielplatz', 'Schulhof', 'Lesebuch'],
    ),
    GermanTask(
      id: 'g2-text-info-library',
      competencyId: GermanCompetencyId.textInformation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Lies den Text. Was leiht Ben aus?',
      prompt: 'Ben geht in die Bücherei. Er leiht ein Buch über Tiere aus.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['ein Buch über Tiere'],
      choices: <String>['ein Buch über Tiere', 'ein Spiel', 'eine Zeitung'],
    ),
    GermanTask(
      id: 'g2-write-sentence-school',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'Lina · geht · zur Schule',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Lina geht zur Schule.',
        'Zur Schule geht Lina.',
      ],
    ),
  ];
}
