import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanVocabularyTouchTaskCatalog {
  const GermanVocabularyTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-family-mark-write',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „schreib-“.',
      prompt: 'Welche Wörter haben denselben Wortstamm und Bedeutungskern?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['schreiben', 'Schreiber', 'Schreibheft'],
      choices: <String>[
        'schreiben',
        'Schreiber',
        'schreien',
        'Schreibheft',
        'Scheibe',
      ],
    ),
    GermanTask(
      id: 'g3-family-mark-play',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „spiel-“.',
      prompt: 'Welche Wörter sind wirklich miteinander verwandt?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['spielen', 'Spieler', 'Spielplatz'],
      choices: <String>[
        'spielen',
        'Spiegel',
        'Spieler',
        'spülen',
        'Spielplatz',
      ],
    ),
    GermanTask(
      id: 'g3-family-mark-drive',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „fahr-“.',
      prompt: 'Welche Wörter gehören zum Bedeutungskern „fahren“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['fahren', 'Fahrer', 'Fahrt'],
      choices: <String>['fahren', 'Farbe', 'Fahrer', 'Falle', 'Fahrt'],
    ),
    GermanTask(
      id: 'g3-family-mark-read',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „les-“.',
      prompt: 'Welche Wörter sind vom Wort „lesen“ abgeleitet?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['lesen', 'Leser', 'lesbar'],
      choices: <String>['lesen', 'leise', 'Leser', 'lösen', 'lesbar'],
    ),
    GermanTask(
      id: 'g3-family-mark-paint',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „mal-“.',
      prompt: 'Welche Wörter gehören zum Bedeutungskern „malen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['malen', 'Maler', 'Bemalung'],
      choices: <String>['malen', 'Maler', 'Mahlzeit', 'Bemalung', 'mal'],
    ),
    GermanTask(
      id: 'g3-family-mark-build',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „bau-“.',
      prompt: 'Welche Wörter gehören zum Bedeutungskern „bauen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['bauen', 'Baustelle', 'bebauen'],
      choices: <String>['bauen', 'Baum', 'Baustelle', 'Bauch', 'bebauen'],
    ),
    GermanTask(
      id: 'g4-family-mark-learn',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „lern-“.',
      prompt:
          'Achte auf Stamm und Bedeutung, nicht nur auf ähnliche Buchstaben.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['lernen', 'Lernstoff', 'erlernen'],
      choices: <String>['lernen', 'Lärm', 'Lernstoff', 'leeren', 'erlernen'],
    ),
    GermanTask(
      id: 'g4-family-mark-work',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „arbeit-“.',
      prompt: 'Welche Wörter tragen denselben Bedeutungskern?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['arbeiten', 'Arbeiter', 'Arbeitszeit'],
      choices: <String>[
        'arbeiten',
        'Arbeiter',
        'Armband',
        'Arbeitszeit',
        'Arzt',
      ],
    ),
    GermanTask(
      id: 'g4-family-mark-live',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „wohn-“.',
      prompt: 'Welche Wörter gehören zum Bedeutungskern „wohnen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['wohnen', 'Wohnung', 'Wohnhaus'],
      choices: <String>['wohnen', 'Wolle', 'Wohnung', 'Wonne', 'Wohnhaus'],
    ),
    GermanTask(
      id: 'g4-family-mark-buy',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „kauf-“.',
      prompt: 'Welche Wörter sind vom Bedeutungskern „kaufen“ abgeleitet?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['kaufen', 'Käufer', 'Einkauf'],
      choices: <String>['kaufen', 'Käufer', 'laufen', 'Einkauf', 'Haufen'],
    ),
    GermanTask(
      id: 'g4-family-mark-read',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „les-“.',
      prompt: 'Auch Vor- und Nachsilben können zum Wortstamm dazukommen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['vorlesen', 'Leserin', 'lesenswert'],
      choices: <String>['vorlesen', 'Leiter', 'Leserin', 'lösen', 'lesenswert'],
    ),
    GermanTask(
      id: 'g4-family-mark-write',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „schreib-“.',
      prompt: 'Finde die Wörter mit gemeinsamem Stamm und Bedeutungskern.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['abschreiben', 'Schreibweise', 'Schreibung'],
      choices: <String>[
        'abschreiben',
        'Schreibweise',
        'Schreie',
        'Schreibung',
        'Scheibe',
      ],
    ),
    GermanTask(
      id: 'g4-compound-build-bike-workshop',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'eine Werkstatt für Fahrräder',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fahrradwerkstatt'],
      choices: <String>['Fahrrad', 'werkstatt', 'wagen'],
    ),
    GermanTask(
      id: 'g4-compound-build-rain-tank',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'ein Behälter für Regenwasser',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Regenwasserbehälter'],
      choices: <String>['Regen', 'wasser', 'behälter', 'regel'],
    ),
    GermanTask(
      id: 'g4-compound-build-children-author',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'ein Autor von Kinderbüchern',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kinderbuchautor'],
      choices: <String>['Kinder', 'buch', 'autor', 'auto'],
    ),
    GermanTask(
      id: 'g4-compound-build-library-card',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'ein Ausweis für die Schulbibliothek',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schulbibliotheksausweis'],
      choices: <String>['Schul', 'bibliotheks', 'ausweis', 'haus'],
    ),
    GermanTask(
      id: 'g4-compound-build-door-key',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'der Schlüssel für die Haustür',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Haustürschlüssel'],
      choices: <String>['Haus', 'tür', 'schlüssel', 'tier'],
    ),
    GermanTask(
      id: 'g4-compound-build-schoolbus-plan',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'der Fahrplan für den Schulbus',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schulbusfahrplan'],
      choices: <String>['Schul', 'bus', 'fahrplan', 'fahrt'],
    ),
  ];
}
