import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanPunctuationTouchTaskCatalog {
  const GermanPunctuationTouchTaskCatalog._();

  static const _sentenceTypeChoices = <String>[
    'Fragesatz',
    'Aussagesatz',
    'Aufforderungssatz',
    '?',
    '.',
    '!',
  ];

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g2-punctuation-pair-heft',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Wo ist dein Heft',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-pair-sun',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Heute scheint die Sonne',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-pair-stop',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Stopp',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-pair-enter',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Komm bitte herein',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-pair-zoo',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Morgen fahren wir zum Zoo',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-pair-key',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Hast du deinen Schlüssel',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-name',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Wie heißt dein Hund',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-rain',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Heute regnet es',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-window',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Öffne bitte das Fenster',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-wednesday',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Heute ist Mittwoch',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-come',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Kommst du heute mit',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-warning',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Pass gut auf',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-pair-school',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Die Schule beginnt um acht Uhr',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g4-direct-build-mia-statement',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Mia kündigt an, dass sie gleich kommt.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Mia sagt: „Ich komme gleich.“'],
      choices: <String>[
        'Mia sagt: „',
        'Ich komme gleich',
        '.“',
        'Mia sagt, „',
        '“.',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-tom-call',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Tom ruft, dass der Bus kommt.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tom ruft: „Der Bus kommt!“'],
      choices: <String>[
        'Tom ruft: „',
        'Der Bus kommt',
        '!“',
        'Tom ruft, „',
        '“!',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-ben-question',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Ben fragt, ob du mitkommst.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Ben fragt: „Kommst du mit?“'],
      choices: <String>[
        'Ben fragt: „',
        'Kommst du mit',
        '?“',
        'Ben fragt, „',
        '“?',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-nora-reply',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Nora antwortet, dass sie morgen kommt.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Nora antwortet: „Ich komme morgen.“'],
      choices: <String>[
        'Nora antwortet: „',
        'Ich komme morgen',
        '.“',
        'Nora antwortet, „',
        '“.',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-lina-question',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Lina fragt nach ihrem Heft.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Lina fragt: „Wo ist mein Heft?“'],
      choices: <String>[
        'Lina fragt: „',
        'Wo ist mein Heft',
        '?“',
        'Lina fragt, „',
        '“?',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-grandpa-call',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit korrekter wörtlicher Rede.',
      prompt: 'Opa ruft, dass alle gut aufpassen sollen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Opa ruft: „Passt gut auf!“'],
      choices: <String>[
        'Opa ruft: „',
        'Passt gut auf',
        '!“',
        'Opa ruft, „',
        '“!',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-lea-after',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Lea sagt, dass sie fertig ist.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Ich bin fertig“, sagt Lea.'],
      choices: <String>[
        '„Ich bin fertig',
        '“, sagt Lea.',
        '.“ sagt Lea.',
        '“ sagt Lea.',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-ben-after',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Ben sagt, dass er gleich startet.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Ich starte gleich“, sagt Ben.'],
      choices: <String>[
        '„Ich starte gleich',
        '“, sagt Ben.',
        '.“ sagt Ben.',
        '“ sagt Ben.',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-mia-after-question',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Mia fragt, ob du morgen kommst.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Kommst du morgen?“, fragt Mia.'],
      choices: <String>[
        '„Kommst du morgen',
        '?“, fragt Mia.',
        '?“ fragt Mia.',
        '“, fragt Mia?',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-tom-after-call',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Tom ruft, dass sofort angehalten werden soll.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Halt sofort an!“, ruft Tom.'],
      choices: <String>[
        '„Halt sofort an',
        '!“, ruft Tom.',
        '!“ ruft Tom.',
        '“, ruft Tom!',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-nora-after',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Nora sagt, dass sie sich um acht treffen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Wir treffen uns um acht“, sagt Nora.'],
      choices: <String>[
        '„Wir treffen uns um acht',
        '“, sagt Nora.',
        '.“ sagt Nora.',
        '“ sagt Nora.',
      ],
    ),
    GermanTask(
      id: 'g4-direct-build-emil-after-question',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue den Satz mit nachgestelltem Begleitsatz.',
      prompt: 'Emil fragt, wo der Ball liegt.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['„Wo liegt der Ball?“, fragt Emil.'],
      choices: <String>[
        '„Wo liegt der Ball',
        '?“, fragt Emil.',
        '?“ fragt Emil.',
        '“, fragt Emil?',
      ],
    ),
  ];
}
