import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanMoreTaskCatalog {
  const GermanMoreTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-letter-sound-s',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe passt zum Laut?',
      prompt: 'sss',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['S'],
      choices: <String>['F', 'S', 'M'],
    ),
    GermanTask(
      id: 'g1-vowel-e',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe ist ein Selbstlaut?',
      prompt: 'Wähle den Selbstlaut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['E'],
      choices: <String>['R', 'E', 'B'],
    ),
    GermanTask(
      id: 'g1-alpha-apple-ball',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort kommt im Alphabet zuerst?',
      prompt: 'Ball · Apfel · Dino',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Apfel'],
      choices: <String>['Ball', 'Apfel', 'Dino'],
    ),
    GermanTask(
      id: 'g1-syllables-banane',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort hat drei Sprechsilben?',
      prompt: 'Sprich die Wörter langsam.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Banane'],
      choices: <String>['Banane', 'Hase', 'Brot'],
    ),
    GermanTask(
      id: 'g1-build-rot',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'R · o · t',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Rot'],
      choices: <String>['Rot', 'Rat', 'Tor'],
    ),
    GermanTask(
      id: 'g1-read-word-regen',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🌧️',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Regen'],
      choices: <String>['Regen', 'Rabe', 'Rose'],
    ),
    GermanTask(
      id: 'g1-sentence-understand-grandma',
      competencyId: GermanCompetencyId.sentenceComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Was backt Oma?',
      prompt: 'Oma backt einen Kuchen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['einen Kuchen'],
      choices: <String>['einen Kuchen', 'ein Brot', 'Kekse'],
    ),
    GermanTask(
      id: 'g1-listen-red-pencil',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör genau zu. Welche Farbe hat der Stift?',
      prompt: 'Tippe auf Lautsprecher und wähle die Farbe.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['rot'],
      choices: <String>['rot', 'blau', 'grün'],
      spokenText: 'Jonas packt einen roten Stift in die Federmappe.',
    ),
    GermanTask(
      id: 'g1-order-mia-reads',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'leise · liest · Mia',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Mia liest leise'],
      choices: <String>['Mia', 'liest', 'leise'],
    ),
    GermanTask(
      id: 'g2-noun-article-window',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Artikel passt?',
      prompt: '___ Fenster',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['das'],
      choices: <String>['der', 'die', 'das'],
    ),
    GermanTask(
      id: 'g2-plural-mouse',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Wie lautet die Mehrzahl?',
      prompt: 'die Maus',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Mäuse'],
      choices: <String>['die Mäuse', 'die Häuser', 'die Kinder'],
    ),
    GermanTask(
      id: 'g2-adjective-warm',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort beschreibt eine Eigenschaft?',
      prompt: 'Der warme Kakao schmeckt gut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['warme'],
      choices: <String>['warme', 'Kakao', 'schmeckt'],
    ),
    GermanTask(
      id: 'g2-verb-sings',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort sagt, was jemand tut?',
      prompt: 'Ella singt ein Lied.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['singt'],
      choices: <String>['Ella', 'singt', 'Lied'],
    ),
    GermanTask(
      id: 'g2-verb-inflect-read',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Form passt in den Satz?',
      prompt: 'Ich ___ ein Buch. · Grundform: lesen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['lese'],
      choices: <String>['lese', 'liest', 'lesen'],
    ),
    GermanTask(
      id: 'g2-punctuation-warning',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Satzzeichen gehört ans Ende?',
      prompt: 'Pass auf',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['!'],
      choices: <String>['.', '?', '!'],
    ),
    GermanTask(
      id: 'g2-sentence-type-statement',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Satzart ist das?',
      prompt: 'Heute ist Mittwoch.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Aussagesatz'],
      choices: <String>['Fragesatz', 'Aussagesatz', 'Aufforderungssatz'],
    ),
    GermanTask(
      id: 'g2-word-family-read',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort gehört zur Wortfamilie von „lesen“?',
      prompt: 'lesen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Lesebuch'],
      choices: <String>['Lesebuch', 'Schultasche', 'Spielplatz'],
    ),
    GermanTask(
      id: 'g2-text-info-tuesday',
      competencyId: GermanCompetencyId.textInformation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Lies den Text. Wann geht Mila schwimmen?',
      prompt: 'Am Montag malt Mila. Am Dienstag geht sie schwimmen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['am Dienstag'],
      choices: <String>['am Montag', 'am Dienstag', 'am Mittwoch'],
    ),
    GermanTask(
      id: 'g2-write-sentence-garden',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'wir · spielen · im Garten',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Wir spielen im Garten.',
        'Im Garten spielen wir.',
      ],
    ),
  ];
}
