import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanMorphologyTouchTaskCatalog {
  const GermanMorphologyTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-syllable-build-lampe',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Lampe',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Lampe'],
      choices: <String>['Lam', 'pe', 'pa'],
    ),
    GermanTask(
      id: 'g1-syllable-build-tomate',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Tomate',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tomate'],
      choices: <String>['To', 'ma', 'te', 'mo'],
    ),
    GermanTask(
      id: 'g1-syllable-build-rakete',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Rakete',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Rakete'],
      choices: <String>['Ra', 'ke', 'te', 'ki'],
    ),
    GermanTask(
      id: 'g1-syllable-build-banane',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Banane',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Banane'],
      choices: <String>['Ba', 'na', 'ne', 'no'],
    ),
    GermanTask(
      id: 'g1-syllable-build-hase',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Hase',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Hase'],
      choices: <String>['Ha', 'se', 'so'],
    ),
    GermanTask(
      id: 'g1-syllable-build-elefant',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Elefant',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Elefant'],
      choices: <String>['E', 'le', 'fant', 'fin'],
    ),
    GermanTask(
      id: 'g1-syllable-build-wolke',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Wolke',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Wolke'],
      choices: <String>['Wol', 'ke', 'ka'],
    ),
    GermanTask(
      id: 'g1-syllable-build-tiger',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Tiger',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tiger'],
      choices: <String>['Ti', 'ger', 'gar'],
    ),
    GermanTask(
      id: 'g2-inflect-go-you-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Du ___ nach Hause. · Grundform: gehen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gehst'],
      choices: <String>['geh', 'st', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-play-he-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Er ___ im Garten. · Grundform: spielen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['spielt'],
      choices: <String>['spiel', 't', 'en'],
    ),
    GermanTask(
      id: 'g2-inflect-jump-we-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Wir ___ über die Pfütze. · Grundform: springen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['springen'],
      choices: <String>['spring', 'en', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-paint-you-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Du ___ ein Bild. · Grundform: malen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['malst'],
      choices: <String>['mal', 'st', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-read-i-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Ich ___ ein Buch. · Grundform: lesen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['lese'],
      choices: <String>['les', 'e', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-run-she-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Sie ___ schnell. · Grundform: rennen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['rennt'],
      choices: <String>['renn', 't', 'en'],
    ),
    GermanTask(
      id: 'g2-inflect-make-you-plural-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Ihr ___ die Tür zu. · Grundform: machen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['macht'],
      choices: <String>['mach', 't', 'en'],
    ),
    GermanTask(
      id: 'g2-inflect-learn-i-build',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Ich ___ für die Schule. · Grundform: lernen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['lerne'],
      choices: <String>['lern', 'e', 't'],
    ),
    GermanTask(
      id: 'g3-tense-play-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform für gestern.',
      prompt: 'Heute spielt Ben. Gestern ___ Ben.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['spielte'],
      choices: <String>['spiel', 'te', 't'],
    ),
    GermanTask(
      id: 'g3-tense-learn-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform für gestern.',
      prompt: 'Heute lernt Mia. Gestern ___ Mia.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['lernte'],
      choices: <String>['lern', 'te', 't'],
    ),
    GermanTask(
      id: 'g3-tense-paint-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform für gestern.',
      prompt: 'Heute malt Lea. Gestern ___ Lea.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['malte'],
      choices: <String>['mal', 'te', 't'],
    ),
    GermanTask(
      id: 'g3-tense-ask-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform für gestern.',
      prompt: 'Heute fragt Tom. Gestern ___ Tom.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['fragte'],
      choices: <String>['frag', 'te', 't'],
    ),
    GermanTask(
      id: 'g4-tense-play-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Ben hat im Garten ___. · Grundform: spielen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gespielt'],
      choices: <String>['ge', 'spiel', 't', 'te'],
    ),
    GermanTask(
      id: 'g4-tense-learn-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Mia hat für die Schule ___. · Grundform: lernen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gelernt'],
      choices: <String>['ge', 'lern', 't', 'en'],
    ),
    GermanTask(
      id: 'g4-tense-paint-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Lea hat ein Bild ___. · Grundform: malen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gemalt'],
      choices: <String>['ge', 'mal', 't', 'te'],
    ),
    GermanTask(
      id: 'g4-tense-ask-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Tom hat seine Lehrerin ___. · Grundform: fragen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gefragt'],
      choices: <String>['ge', 'frag', 't', 'te'],
    ),
  ];
}
