import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanUpperPrimaryTaskCatalog {
  const GermanUpperPrimaryTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-spelling-strategy-tag',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches Wort hilft dir bei der Endung von „Tag“?',
      prompt: 'Du möchtest prüfen, ob du am Ende g oder k schreibst.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tage'],
      choices: <String>['Tage', 'Tag', 'tagsüber'],
    ),
    GermanTask(
      id: 'g3-spelling-strategy-haeuser',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches verwandte Wort hilft dir bei „Häuser“?',
      prompt: 'Prüfe, warum „Häuser“ mit äu geschrieben wird.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Haus'],
      choices: <String>['Haus', 'Hase', 'Heu'],
    ),
    GermanTask(
      id: 'g3-spelling-strategy-hand',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Strategie hilft bei „Hand“?',
      prompt: 'Du bist bei d oder t am Wortende unsicher.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Verlängern: Hände'],
      choices: <String>[
        'Verlängern: Hände',
        'Artikel wechseln',
        'Nur schneller sprechen',
      ],
    ),
    GermanTask(
      id: 'g3-dictionary-order',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches Wort findest du im Wörterbuch zuerst?',
      prompt: 'Kanne · Kante · Katze',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Kanne'],
      choices: <String>['Kanne', 'Kante', 'Katze'],
    ),
    GermanTask(
      id: 'g3-dictionary-lief',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Unter welcher Grundform suchst du „lief“?',
      prompt: 'Finde die passende Wörterbuchform.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['laufen'],
      choices: <String>['laufen', 'lief', 'Lauf'],
    ),
    GermanTask(
      id: 'g3-dictionary-groesser',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Unter welcher Grundform suchst du „größer“?',
      prompt: 'Denke an die Grundform des Adjektivs.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['groß'],
      choices: <String>['groß', 'Größe', 'größer'],
    ),
    GermanTask(
      id: 'g3-compound-haustuer',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Aus welchen Wörtern besteht „Haustür“?',
      prompt: 'Zerlege das zusammengesetzte Nomen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Haus + Tür'],
      choices: <String>['Haus + Tür', 'Haut + Tür', 'Haus + Tier'],
    ),
    GermanTask(
      id: 'g3-compound-regenjacke',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche zwei Wörter bilden „Regenjacke“?',
      prompt: 'Finde die beiden bedeutungstragenden Teile.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Regen + Jacke'],
      choices: <String>['Regen + Jacke', 'Regel + Jacke', 'Regen + Decke'],
    ),
    GermanTask(
      id: 'g3-compound-schulweg',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches zusammengesetzte Wort passt?',
      prompt: 'der Weg zur Schule',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Schulweg'],
      choices: <String>['Schulweg', 'Gehweg', 'Waldweg'],
    ),
    GermanTask(
      id: 'g3-subject-dog',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist das Subjekt?',
      prompt: 'Der kleine Hund bellt laut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Der kleine Hund'],
      choices: <String>['Der kleine Hund', 'bellt', 'laut'],
    ),
    GermanTask(
      id: 'g3-predicate-play',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist das Prädikat?',
      prompt: 'Im Hof spielen die Kinder.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['spielen'],
      choices: <String>['spielen', 'die Kinder', 'Im Hof'],
    ),
    GermanTask(
      id: 'g3-subject-build',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Wer oder was baut eine Burg?',
      prompt: 'Mia und Ben bauen eine Burg.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Mia und Ben'],
      choices: <String>['Mia und Ben', 'bauen', 'eine Burg'],
    ),
    GermanTask(
      id: 'g3-constituent-when',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Wann?“',
      prompt: 'Am Morgen fährt Lea mit dem Bus.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Am Morgen'],
      choices: <String>['Am Morgen', 'Lea', 'mit dem Bus'],
    ),
    GermanTask(
      id: 'g3-constituent-where',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Wo?“',
      prompt: 'Im Garten baut Tom eine Hütte.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Im Garten'],
      choices: <String>['Im Garten', 'Tom', 'eine Hütte'],
    ),
    GermanTask(
      id: 'g3-constituent-how',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Womit?“',
      prompt: 'Mit dem Fahrrad fährt Mia zur Schule.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Mit dem Fahrrad'],
      choices: <String>['Mit dem Fahrrad', 'Mia', 'zur Schule'],
    ),
    GermanTask(
      id: 'g3-tense-play',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Verbform passt zu „gestern“?',
      prompt: 'Heute spielt Ben. Gestern ___ Ben.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['spielte'],
      choices: <String>['spielte', 'spielt', 'spielen'],
    ),
    GermanTask(
      id: 'g3-tense-go',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze den Satz in die Vergangenheit.',
      prompt: 'Heute gehen wir zum See. Gestern ___ wir zum See.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['gingen'],
      choices: <String>['gingen', 'gehen', 'geht'],
    ),
    GermanTask(
      id: 'g3-tense-recognize',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'In welcher Zeitform steht der Satz?',
      prompt: 'Mia malte ein Bild.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Vergangenheit'],
      choices: <String>['Vergangenheit', 'Gegenwart', 'Zukunft'],
    ),
    GermanTask(
      id: 'g3-inference-rain',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was kannst du aus dem Text schließen?',
      prompt:
          'Der Gehweg glänzt. Lina spannt ihren Schirm auf und springt über eine Pfütze.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Es regnet oder hat gerade geregnet.'],
      choices: <String>[
        'Es regnet oder hat gerade geregnet.',
        'Es ist sehr heiß und trocken.',
        'Es liegt Schnee.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-birthday',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist wahrscheinlich der Anlass?',
      prompt:
          'Jonas pustet acht Kerzen aus. Alle klatschen und danach wird Kuchen verteilt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Jonas hat Geburtstag.'],
      choices: <String>[
        'Jonas hat Geburtstag.',
        'Jonas schreibt einen Test.',
        'Jonas fährt in den Urlaub.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-cold',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Schlussfolgerung passt?',
      prompt:
          'Lea zieht Mütze, Schal und dicke Handschuhe an, bevor sie nach draußen geht.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Draußen ist es kalt.'],
      choices: <String>[
        'Draußen ist es kalt.',
        'Draußen ist es sehr warm.',
        'Lea geht schwimmen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-plant',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was geschieht zuerst?',
      prompt:
          'Mia füllt Erde in einen Topf. Dann setzt sie einen Samen hinein. Zum Schluss gießt sie vorsichtig.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Erde in den Topf füllen'],
      choices: <String>[
        'Erde in den Topf füllen',
        'den Samen einsetzen',
        'gießen',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-salad',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was passiert nach dem Waschen?',
      prompt:
          'Zuerst wäscht Ben die Tomaten. Danach schneidet er sie klein. Anschließend gibt er sie in die Schüssel.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Er schneidet die Tomaten klein.'],
      choices: <String>[
        'Er schneidet die Tomaten klein.',
        'Er wäscht die Tomaten.',
        'Er stellt die Schüssel weg.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-library',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was geschieht zuletzt?',
      prompt:
          'Nora sucht ein Buch aus. Sie leiht es am Schalter aus. Zu Hause beginnt sie sofort zu lesen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Nora beginnt zu lesen.'],
      choices: <String>[
        'Nora beginnt zu lesen.',
        'Nora sucht ein Buch aus.',
        'Nora leiht das Buch aus.',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-bees',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Überschrift fasst den Text am besten zusammen?',
      prompt:
          'Bienen sammeln Nektar und bestäuben dabei viele Blüten. Dadurch helfen sie zahlreichen Pflanzen, Früchte und Samen zu bilden.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Warum Bienen für Pflanzen wichtig sind'],
      choices: <String>[
        'Warum Bienen für Pflanzen wichtig sind',
        'Wie man Honigkuchen backt',
        'Warum Blüten bunt sind',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-recycling',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was ist die Kernaussage?',
      prompt:
          'Die Klasse sammelt eine Woche lang Altpapier. Am Freitag bringen die Kinder es gemeinsam zum Container. Sie wollen weniger Papier wegwerfen und Rohstoffe sparen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Die Klasse sammelt Papier, um Ressourcen zu sparen.',
      ],
      choices: <String>[
        'Die Klasse sammelt Papier, um Ressourcen zu sparen.',
        'Am Freitag fällt der Unterricht aus.',
        'Die Kinder kaufen neue Hefte.',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-birds',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Zusammenfassung passt am besten?',
      prompt:
          'Im Herbst ziehen viele Zugvögel in wärmere Gebiete. Dort finden sie im Winter leichter Nahrung. Im Frühling kehren viele Arten zurück.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Zugvögel wechseln je nach Jahreszeit ihr Gebiet.',
      ],
      choices: <String>[
        'Zugvögel wechseln je nach Jahreszeit ihr Gebiet.',
        'Alle Vögel bleiben im Winter hier.',
        'Vögel finden nur im Frühling Nahrung.',
      ],
    ),
    GermanTask(
      id: 'g4-connect-rain',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Wort verbindet die Gedanken passend?',
      prompt: 'Es regnet stark. ___ nimmt Mia einen Schirm mit.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Deshalb'],
      choices: <String>['Deshalb', 'Trotzdem', 'Oder'],
    ),
    GermanTask(
      id: 'g4-connect-sick',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Verbindungswort passt?',
      prompt: 'Ben bleibt heute zu Hause, ___ er krank ist.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['weil'],
      choices: <String>['weil', 'danach', 'aber'],
    ),
    GermanTask(
      id: 'g4-connect-sequence',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Wort zeigt die zeitliche Reihenfolge?',
      prompt: 'Lina packt ihre Tasche. ___ fährt sie zur Schule.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Danach'],
      choices: <String>['Danach', 'Weil', 'Obwohl'],
    ),
    GermanTask(
      id: 'g4-revision-repetition',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Fassung vermeidet unnötige Wiederholungen?',
      prompt: 'Der Hund läuft zum Tor. Der Hund wartet dort. Der Hund bellt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Der Hund läuft zum Tor. Dort wartet er und bellt.',
      ],
      choices: <String>[
        'Der Hund läuft zum Tor. Dort wartet er und bellt.',
        'Der Hund läuft zum Tor. Der Hund wartet dort. Der Hund bellt.',
        'Hund Tor warten bellen.',
      ],
    ),
    GermanTask(
      id: 'g4-revision-order',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Fassung macht den Ablauf besonders klar?',
      prompt: 'Ich zog die Schuhe an. Ich band die Schnürsenkel. Ich ging los.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Zuerst zog ich die Schuhe an. Dann band ich die Schnürsenkel. Danach ging ich los.',
      ],
      choices: <String>[
        'Zuerst zog ich die Schuhe an. Dann band ich die Schnürsenkel. Danach ging ich los.',
        'Ich ging los. Ich zog die Schuhe an. Ich band die Schnürsenkel.',
        'Schuhe, Schnürsenkel, los.',
      ],
    ),
    GermanTask(
      id: 'g4-revision-precise',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Formulierung ist genauer und anschaulicher?',
      prompt: 'Der Fuchs bewegte sich sehr schnell über die Wiese.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Der Fuchs rannte über die Wiese.'],
      choices: <String>[
        'Der Fuchs rannte über die Wiese.',
        'Der Fuchs machte etwas auf der Wiese.',
        'Der Fuchs war auf der Wiese.',
      ],
    ),
    GermanTask(
      id: 'g4-listen-mainidea-trip',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Hör zu. Worum geht es hauptsächlich?',
      prompt: 'Tippe auf Anhören und wähle die Kernaussage.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Die Klasse plant einen Ausflug in den Wald.'],
      choices: <String>[
        'Die Klasse plant einen Ausflug in den Wald.',
        'Die Klasse schreibt heute einen Mathetest.',
        'Die Klasse baut ein neues Schulhaus.',
      ],
      spokenText:
          'Am Freitag möchte die Klasse gemeinsam in den Wald wandern. Die Kinder sollen feste Schuhe, eine Trinkflasche und eine kleine Brotzeit mitbringen.',
    ),
    GermanTask(
      id: 'g4-listen-mainidea-library',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Information ist am wichtigsten?',
      prompt: 'Hör den Hinweis und wähle die Hauptaussage.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Die Bücherei schließt heute früher.'],
      choices: <String>[
        'Die Bücherei schließt heute früher.',
        'Alle Bücher sind ausgeliehen.',
        'Die Bücherei zieht in eine andere Stadt.',
      ],
      spokenText:
          'Achtung: Wegen einer Veranstaltung schließt die Bücherei heute bereits um sechzehn Uhr. Ausgeliehene Bücher können morgen wieder abgegeben werden.',
    ),
    GermanTask(
      id: 'g4-listen-mainidea-sports',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was ist die Kernaussage der Ansage?',
      prompt: 'Hör genau zu und entscheide.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Das Sportfest wird in die Turnhalle verlegt.'],
      choices: <String>[
        'Das Sportfest wird in die Turnhalle verlegt.',
        'Das Sportfest fällt für immer aus.',
        'Das Sportfest beginnt eine Woche später.',
      ],
      spokenText:
          'Weil es am Vormittag stark regnen soll, findet das Sportfest nicht auf dem Sportplatz, sondern in der Turnhalle statt. Die Startzeit bleibt neun Uhr.',
    ),
    GermanTask(
      id: 'g4-direct-speech-statement',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satz ist richtig geschrieben?',
      prompt: 'Mia kündigt an, dass sie gleich kommt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Mia sagt: „Ich komme gleich.“'],
      choices: <String>[
        'Mia sagt: „Ich komme gleich.“',
        'Mia sagt „Ich komme gleich“.',
        'Mia sagt, „Ich komme gleich.“',
      ],
    ),
    GermanTask(
      id: 'g4-direct-speech-question',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Zeichensetzung passt?',
      prompt: 'Ben stellt die Frage: Kommst du mit?',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Ben fragt: „Kommst du mit?“'],
      choices: <String>[
        'Ben fragt: „Kommst du mit?“',
        'Ben fragt „Kommst du mit“?',
        'Ben fragt, „Kommst du mit?“',
      ],
    ),
    GermanTask(
      id: 'g4-direct-speech-after',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satz mit nachgestelltem Begleitsatz ist richtig?',
      prompt: 'Lea sagt, dass sie fertig ist.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['„Ich bin fertig“, sagt Lea.'],
      choices: <String>[
        '„Ich bin fertig“, sagt Lea.',
        '„Ich bin fertig.“ sagt Lea.',
        '„Ich bin fertig“ sagt Lea.',
      ],
    ),
  ];
}
