import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanPhonicsListeningTaskCatalog {
  const GermanPhonicsListeningTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-phonics-listen-mouse',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['M'],
      choices: <String>['M', 'N', 'L'],
      spokenText: 'Maus',
    ),
    GermanTask(
      id: 'g1-phonics-listen-lamp',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['L'],
      choices: <String>['R', 'L', 'M'],
      spokenText: 'Lampe',
    ),
    GermanTask(
      id: 'g1-phonics-listen-fish',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['F'],
      choices: <String>['W', 'F', 'S'],
      spokenText: 'Fisch',
    ),
    GermanTask(
      id: 'g1-phonics-listen-rose',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['R'],
      choices: <String>['L', 'R', 'N'],
      spokenText: 'Rose',
    ),
    GermanTask(
      id: 'g1-phonics-listen-nose',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['N'],
      choices: <String>['M', 'N', 'R'],
      spokenText: 'Nase',
    ),
    GermanTask(
      id: 'g1-phonics-listen-ball',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['B'],
      choices: <String>['P', 'D', 'B'],
      spokenText: 'Ball',
    ),
    GermanTask(
      id: 'g1-phonics-listen-cat',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['K'],
      choices: <String>['G', 'T', 'K'],
      spokenText: 'Katze',
    ),
    GermanTask(
      id: 'g1-phonics-listen-cup',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['T'],
      choices: <String>['D', 'T', 'P'],
      spokenText: 'Tasse',
    ),
    GermanTask(
      id: 'g1-phonics-listen-brush',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['P'],
      choices: <String>['B', 'P', 'T'],
      spokenText: 'Pinsel',
    ),
    GermanTask(
      id: 'g1-phonics-listen-house',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['H'],
      choices: <String>['H', 'F', 'K'],
      spokenText: 'Haus',
    ),
    GermanTask(
      id: 'g1-phonics-listen-can',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['D'],
      choices: <String>['T', 'B', 'D'],
      spokenText: 'Dose',
    ),
    GermanTask(
      id: 'g1-phonics-listen-fork',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['G'],
      choices: <String>['K', 'G', 'B'],
      spokenText: 'Gabel',
    ),
    GermanTask(
      id: 'g1-phonics-listen-cloud',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['W'],
      choices: <String>['F', 'W', 'M'],
      spokenText: 'Wolke',
    ),
    GermanTask(
      id: 'g1-phonics-listen-apple',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['A'],
      choices: <String>['A', 'E', 'O'],
      spokenText: 'Apfel',
    ),
    GermanTask(
      id: 'g1-phonics-listen-duck',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['E'],
      choices: <String>['I', 'E', 'A'],
      spokenText: 'Ente',
    ),
    GermanTask(
      id: 'g1-phonics-listen-hedgehog',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['I'],
      choices: <String>['E', 'I', 'U'],
      spokenText: 'Igel',
    ),
    GermanTask(
      id: 'g1-phonics-listen-oven',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['O'],
      choices: <String>['A', 'U', 'O'],
      spokenText: 'Ofen',
    ),
    GermanTask(
      id: 'g1-phonics-listen-clock',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['U'],
      choices: <String>['O', 'U', 'I'],
      spokenText: 'Uhr',
    ),
    GermanTask(
      id: 'g1-phonics-listen-sun',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['S'],
      choices: <String>['S', 'F', 'Z'],
      spokenText: 'Sonne',
    ),
    GermanTask(
      id: 'g1-phonics-listen-zebra',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör das Wort. Welcher Buchstabe passt zum ersten Laut?',
      prompt: 'Hör das Wort an.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Z'],
      choices: <String>['S', 'Z', 'T'],
      spokenText: 'Zebra',
    ),
  ];
}
