import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanSentenceStructureExpansionTaskCatalog {
  const GermanSentenceStructureExpansionTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-order-library-return',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Am Freitag“ beginnt.',
      prompt: 'Am Freitag · gibt · Nora · das Buch · in der Bücherei · zurück',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Am Freitag gibt Nora das Buch in der Bücherei zurück',
      ],
      choices: <String>[
        'Am Freitag',
        'gibt',
        'Nora',
        'das Buch',
        'in der Bücherei',
        'zurück',
      ],
    ),
    GermanTask(
      id: 'g3-order-bus-arrive',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Nach zehn Minuten“ beginnt.',
      prompt: 'Nach zehn Minuten · kommt · der Bus · an der Haltestelle · an',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Nach zehn Minuten kommt der Bus an der Haltestelle an',
      ],
      choices: <String>[
        'Nach zehn Minuten',
        'kommt',
        'der Bus',
        'an der Haltestelle',
        'an',
      ],
    ),
    GermanTask(
      id: 'g3-order-window-open',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Baue den Satz so, dass er mit „Vor dem Unterricht“ beginnt.',
      prompt: 'Vor dem Unterricht · macht · Ben · das Fenster · auf',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Vor dem Unterricht macht Ben das Fenster auf'],
      choices: <String>[
        'Vor dem Unterricht',
        'macht',
        'Ben',
        'das Fenster',
        'auf',
      ],
    ),
    GermanTask(
      id: 'g3-order-grandma-call',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Am Abend“ beginnt.',
      prompt: 'Am Abend · ruft · Mia · ihre Oma · an',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Am Abend ruft Mia ihre Oma an'],
      choices: <String>['Am Abend', 'ruft', 'Mia', 'ihre Oma', 'an'],
    ),
    GermanTask(
      id: 'g3-order-schoolbag-pack',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Vor dem Schlafen“ beginnt.',
      prompt: 'Vor dem Schlafen · packt · Leo · seinen Ranzen · ein',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Vor dem Schlafen packt Leo seinen Ranzen ein'],
      choices: <String>[
        'Vor dem Schlafen',
        'packt',
        'Leo',
        'seinen Ranzen',
        'ein',
      ],
    ),
    GermanTask(
      id: 'g3-order-light-switch',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Nach dem Film“ beginnt.',
      prompt: 'Nach dem Film · schaltet · Papa · das Licht · wieder · ein',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Nach dem Film schaltet Papa das Licht wieder ein',
      ],
      choices: <String>[
        'Nach dem Film',
        'schaltet',
        'Papa',
        'das Licht',
        'wieder',
        'ein',
      ],
    ),
    GermanTask(
      id: 'g3-order-notebook-take',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Für die Stunde“ beginnt.',
      prompt: 'Für die Stunde · nimmt · Sara · ihr Heft · heraus',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Für die Stunde nimmt Sara ihr Heft heraus'],
      choices: <String>[
        'Für die Stunde',
        'nimmt',
        'Sara',
        'ihr Heft',
        'heraus',
      ],
    ),
    GermanTask(
      id: 'g3-order-shoes-put-on',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Vor der Pause“ beginnt.',
      prompt: 'Vor der Pause · zieht · Amir · seine Schuhe · an',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Vor der Pause zieht Amir seine Schuhe an'],
      choices: <String>['Vor der Pause', 'zieht', 'Amir', 'seine Schuhe', 'an'],
    ),
    GermanTask(
      id: 'g3-order-story-read',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Nach der Arbeit“ beginnt.',
      prompt:
          'Nach der Arbeit · liest · Opa · den Kindern · eine Geschichte · vor',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Nach der Arbeit liest Opa den Kindern eine Geschichte vor',
      ],
      choices: <String>[
        'Nach der Arbeit',
        'liest',
        'Opa',
        'den Kindern',
        'eine Geschichte',
        'vor',
      ],
    ),
    GermanTask(
      id: 'g3-order-bike-lock',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue den Satz so, dass er mit „Vor der Schule“ beginnt.',
      prompt: 'Vor der Schule · schließt · Lina · ihr Fahrrad · ab',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Vor der Schule schließt Lina ihr Fahrrad ab'],
      choices: <String>[
        'Vor der Schule',
        'schließt',
        'Lina',
        'ihr Fahrrad',
        'ab',
      ],
    ),
    GermanTask(
      id: 'g3-write-morning-bus',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'am Morgen · fährt Nora · mit dem Bus · zur Schule',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Am Morgen fährt Nora mit dem Bus zur Schule.',
        'Nora fährt am Morgen mit dem Bus zur Schule.',
      ],
    ),
    GermanTask(
      id: 'g3-write-library-book',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'in der Bücherei · leiht Ben · ein Sachbuch · aus',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'In der Bücherei leiht Ben ein Sachbuch aus.',
        'Ben leiht in der Bücherei ein Sachbuch aus.',
      ],
    ),
    GermanTask(
      id: 'g3-write-after-school-grandma',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'nach der Schule · besucht Mia · ihre Oma',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Nach der Schule besucht Mia ihre Oma.',
        'Mia besucht nach der Schule ihre Oma.',
      ],
    ),
    GermanTask(
      id: 'g3-write-garden-bird',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'im Garten · beobachtet Tom · einen kleinen Vogel',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Im Garten beobachtet Tom einen kleinen Vogel.',
        'Tom beobachtet im Garten einen kleinen Vogel.',
      ],
    ),
    GermanTask(
      id: 'g3-write-project-model',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'für das Projekt · baut die Gruppe · ein Modell · aus Karton',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Für das Projekt baut die Gruppe ein Modell aus Karton.',
        'Die Gruppe baut für das Projekt ein Modell aus Karton.',
      ],
    ),
    GermanTask(
      id: 'g3-write-evening-call',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'am Abend · ruft Lea · ihren Bruder · an',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Am Abend ruft Lea ihren Bruder an.',
        'Lea ruft am Abend ihren Bruder an.',
      ],
    ),
    GermanTask(
      id: 'g3-write-rain-jacket',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'wegen des Regens · zieht Paul · seine Jacke · an',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Wegen des Regens zieht Paul seine Jacke an.',
        'Paul zieht wegen des Regens seine Jacke an.',
      ],
    ),
    GermanTask(
      id: 'g3-write-break-window',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Schreibe aus den Satzbausteinen einen vollständigen Satz.',
      prompt: 'vor der Pause · öffnet Sara · vorsichtig · das Fenster',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Vor der Pause öffnet Sara vorsichtig das Fenster.',
        'Sara öffnet vor der Pause vorsichtig das Fenster.',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-rest-separable',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und alle Teile des Prädikats.',
      prompt: 'Nach dem Training ruhen sich die Spieler aus.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Spieler', 'ruhen', 'sich aus'],
      choices: <String>[
        'Nach dem Training',
        'ruhen',
        'sich aus',
        'die Spieler',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-prepare-separable',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und alle Teile des Prädikats.',
      prompt: 'Morgen bereitet die Klasse das Fest vor.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Klasse', 'bereitet', 'vor'],
      choices: <String>['Morgen', 'bereitet', 'die Klasse', 'das Fest', 'vor'],
    ),
    GermanTask(
      id: 'g4-subpred-letter-perfect',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Am Abend hat Mia einen langen Brief geschrieben.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Mia', 'hat', 'geschrieben'],
      choices: <String>[
        'Am Abend',
        'hat',
        'Mia',
        'einen langen Brief',
        'geschrieben',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-model-perfect',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Für das Projekt haben die Kinder ein Modell gebaut.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Kinder', 'haben', 'gebaut'],
      choices: <String>[
        'Für das Projekt',
        'haben',
        'die Kinder',
        'ein Modell',
        'gebaut',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-bike-modal',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Nach der Schule will Ben sein Fahrrad reparieren.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Ben', 'will', 'reparieren'],
      choices: <String>[
        'Nach der Schule',
        'will',
        'Ben',
        'sein Fahrrad',
        'reparieren',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-book-modal',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Heute möchte Lea das neue Buch ausleihen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Lea', 'möchte', 'ausleihen'],
      choices: <String>['Heute', 'möchte', 'Lea', 'das neue Buch', 'ausleihen'],
    ),
    GermanTask(
      id: 'g4-subpred-door-separable',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und alle Teile des Prädikats.',
      prompt: 'Vor dem Unterricht schließt der Hausmeister die Tür auf.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['der Hausmeister', 'schließt', 'auf'],
      choices: <String>[
        'Vor dem Unterricht',
        'schließt',
        'der Hausmeister',
        'die Tür',
        'auf',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-window-separable',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und alle Teile des Prädikats.',
      prompt: 'Am Morgen macht Nora vorsichtig das Fenster zu.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Nora', 'macht', 'zu'],
      choices: <String>[
        'Am Morgen',
        'macht',
        'Nora',
        'vorsichtig',
        'das Fenster',
        'zu',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-bus-past',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Gestern ist der Bus sehr spät angekommen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['der Bus', 'ist', 'angekommen'],
      choices: <String>['Gestern', 'ist', 'der Bus', 'sehr spät', 'angekommen'],
    ),
    GermanTask(
      id: 'g4-subpred-children-future',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Morgen werden die Kinder den Versuch wiederholen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Kinder', 'werden', 'wiederholen'],
      choices: <String>[
        'Morgen',
        'werden',
        'die Kinder',
        'den Versuch',
        'wiederholen',
      ],
    ),
    GermanTask(
      id: 'g4-subpred-dog-perfect',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Im Garten hat der Hund laut gebellt.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['der Hund', 'hat', 'gebellt'],
      choices: <String>['Im Garten', 'hat', 'der Hund', 'laut', 'gebellt'],
    ),
    GermanTask(
      id: 'g4-subpred-class-modal',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere das Subjekt und das vollständige Prädikat.',
      prompt: 'Für das Fest soll die Klasse ein Lied einüben.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Klasse', 'soll', 'einüben'],
      choices: <String>[
        'Für das Fest',
        'soll',
        'die Klasse',
        'ein Lied',
        'einüben',
      ],
    ),
  ];
}
