import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanWordRecognitionTaskCatalog {
  const GermanWordRecognitionTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-read-word-ball',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: ⚽',
      accessiblePrompt: 'Ein rundes Spielgerät, das rollen und springen kann.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Ball'],
      choices: <String>['Ball', 'Fall', 'Bald'],
    ),
    GermanTask(
      id: 'g1-read-word-brot',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🍞',
      accessiblePrompt:
          'Ein Lebensmittel aus Mehl, das oft in Scheiben geschnitten wird.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Brot'],
      choices: <String>['Brot', 'Boot', 'Brett'],
    ),
    GermanTask(
      id: 'g1-read-word-mond',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🌙',
      accessiblePrompt: 'Etwas Helles ist nachts am Himmel zu sehen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Mond'],
      choices: <String>['Mond', 'Mund', 'Mohn'],
    ),
    GermanTask(
      id: 'g1-read-word-fisch',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🐟',
      accessiblePrompt: 'Ein Tier lebt im Wasser und bewegt sich mit Flossen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Fisch'],
      choices: <String>['Fisch', 'Tisch', 'Fink'],
    ),
    GermanTask(
      id: 'g1-read-word-katze',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🐱',
      accessiblePrompt: 'Ein Haustier mit Schnurrhaaren, das miauen kann.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Katze'],
      choices: <String>['Katze', 'Tatze', 'Karte'],
    ),
    GermanTask(
      id: 'g1-read-word-hund',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🐶',
      accessiblePrompt:
          'Ein Haustier, das bellen und mit dem Schwanz wedeln kann.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hund'],
      choices: <String>['Hund', 'Mund', 'Hand'],
    ),
    GermanTask(
      id: 'g1-read-word-maus',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🐭',
      accessiblePrompt: 'Ein kleines Tier mit langem Schwanz und runden Ohren.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Maus'],
      choices: <String>['Maus', 'Haus', 'Mais'],
    ),
    GermanTask(
      id: 'g1-read-word-auto',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🚗',
      accessiblePrompt: 'Ein Fahrzeug mit vier Rädern fährt auf der Straße.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Auto'],
      choices: <String>['Auto', 'Auge', 'Aula'],
    ),
    GermanTask(
      id: 'g1-read-word-apfel',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🍎',
      accessiblePrompt: 'Eine runde Frucht kann rot oder grün sein.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Apfel'],
      choices: <String>['Apfel', 'Ampel', 'Affe'],
    ),
    GermanTask(
      id: 'g1-read-word-baum',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🌳',
      accessiblePrompt: 'Eine große Pflanze hat einen Stamm und viele Äste.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Baum'],
      choices: <String>['Baum', 'Raum', 'Bauch'],
    ),
    GermanTask(
      id: 'g1-read-word-buch',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 📖',
      accessiblePrompt:
          'Viele bedruckte Seiten sind zusammengebunden und können gelesen werden.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Buch'],
      choices: <String>['Buch', 'Bach', 'Busch'],
    ),
    GermanTask(
      id: 'g1-read-word-hand',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: ✋',
      accessiblePrompt: 'Ein Körperteil hat fünf Finger.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hand'],
      choices: <String>['Hand', 'Wand', 'Hund'],
    ),
    GermanTask(
      id: 'g1-read-word-nase',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 👃',
      accessiblePrompt: 'Mit diesem Körperteil kann man riechen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Nase'],
      choices: <String>['Nase', 'Hase', 'Nuss'],
    ),
    GermanTask(
      id: 'g1-read-word-hose',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 👖',
      accessiblePrompt: 'Ein Kleidungsstück bedeckt die Beine.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hose'],
      choices: <String>['Hose', 'Rose', 'Hase'],
    ),
    GermanTask(
      id: 'g1-read-word-tasse',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: ☕',
      accessiblePrompt: 'Ein Trinkgefäß hat oft einen Henkel.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tasse'],
      choices: <String>['Tasse', 'Tasche', 'Tanne'],
    ),
    GermanTask(
      id: 'g1-read-word-pinsel',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🖌️',
      accessiblePrompt: 'Ein Werkzeug mit Borsten wird zum Malen benutzt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Pinsel'],
      choices: <String>['Pinsel', 'Insel', 'Pilz'],
    ),
    GermanTask(
      id: 'g1-read-word-stern',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: ⭐',
      accessiblePrompt: 'Ein heller Punkt ist nachts am Himmel zu sehen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Stern'],
      choices: <String>['Stern', 'Stein', 'Stift'],
    ),
    GermanTask(
      id: 'g1-read-word-tuer',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort passt zum Bild?',
      prompt: 'Bild: 🚪',
      accessiblePrompt: 'Damit kann man einen Eingang öffnen und schließen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tür'],
      choices: <String>['Tür', 'Tier', 'Turm'],
    ),
  ];
}
