import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanOrderingTouchTaskCatalog {
  const GermanOrderingTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-alpha-order-animals-1',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Hund · Katze · Maus',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Hund Katze Maus'],
      choices: <String>['Hund', 'Katze', 'Maus'],
    ),
    GermanTask(
      id: 'g1-alpha-order-things-1',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Dino · Apfel · Ball',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Apfel Ball Dino'],
      choices: <String>['Dino', 'Apfel', 'Ball'],
    ),
    GermanTask(
      id: 'g1-alpha-order-animals-2',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Zebra · Bär · Fisch',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Bär Fisch Zebra'],
      choices: <String>['Zebra', 'Bär', 'Fisch'],
    ),
    GermanTask(
      id: 'g1-alpha-order-things-2',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Tasse · Lampe · Rose',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Lampe Rose Tasse'],
      choices: <String>['Tasse', 'Lampe', 'Rose'],
    ),
    GermanTask(
      id: 'g1-alpha-order-animals-3',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Igel · Esel · Affe',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Affe Esel Igel'],
      choices: <String>['Igel', 'Esel', 'Affe'],
    ),
    GermanTask(
      id: 'g1-alpha-order-nature',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Wolke · Baum · Sonne',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Baum Sonne Wolke'],
      choices: <String>['Wolke', 'Baum', 'Sonne'],
    ),
    GermanTask(
      id: 'g1-alpha-order-school',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Tafel · Heft · Stift',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Heft Stift Tafel'],
      choices: <String>['Tafel', 'Heft', 'Stift'],
    ),
    GermanTask(
      id: 'g1-alpha-order-food',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Milch · Brot · Apfel',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Apfel Brot Milch'],
      choices: <String>['Milch', 'Brot', 'Apfel'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-band',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Bart · Bank · Band',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Band Bank Bart'],
      choices: <String>['Bart', 'Bank', 'Band'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-kanne',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Katze · Kante · Kanne',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Kanne Kante Katze'],
      choices: <String>['Katze', 'Kante', 'Kanne'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-gabel',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Garten · Gans · Gabel',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Gabel Gans Garten'],
      choices: <String>['Garten', 'Gans', 'Gabel'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-maler',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Mappe · Mantel · Maler',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Maler Mantel Mappe'],
      choices: <String>['Mappe', 'Mantel', 'Maler'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-sch',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Schule · Schrank · Schlange',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Schlange Schrank Schule'],
      choices: <String>['Schule', 'Schrank', 'Schlange'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-sche',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Schrank · Schiff · Schere',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Schere Schiff Schrank'],
      choices: <String>['Schrank', 'Schiff', 'Schere'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-kra',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Kram · Kralle · Kragen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Kragen Kralle Kram'],
      choices: <String>['Kram', 'Kralle', 'Kragen'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-bla',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Blau · Blatt · Blase',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Blase Blatt Blau'],
      choices: <String>['Blau', 'Blatt', 'Blase'],
    ),
    GermanTask(
      id: 'g3-sequence-cocoa-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Kakao zubereiten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Milch erwärmen. Kakao einrühren. In die Tasse gießen.',
      ],
      choices: <String>[
        'In die Tasse gießen.',
        'Kakao einrühren.',
        'Milch erwärmen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-bike-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Fahrrad fahrbereit machen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Fahrrad holen. Reifen prüfen. Luft aufpumpen. Losfahren.',
      ],
      choices: <String>[
        'Losfahren.',
        'Luft aufpumpen.',
        'Fahrrad holen.',
        'Reifen prüfen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-sandwich-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Ein Käsebrot machen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Brot hinlegen. Käse auflegen. Zweite Scheibe darauflegen. Brot halbieren.',
      ],
      choices: <String>[
        'Brot halbieren.',
        'Käse auflegen.',
        'Brot hinlegen.',
        'Zweite Scheibe darauflegen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-plant-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Einen Samen einpflanzen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Erde in den Topf füllen. Samen einsetzen. Vorsichtig gießen. Topf ans Licht stellen.',
      ],
      choices: <String>[
        'Topf ans Licht stellen.',
        'Samen einsetzen.',
        'Vorsichtig gießen.',
        'Erde in den Topf füllen.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-library-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Ein Buch in der Bücherei ausleihen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Im Katalog suchen. Regalnummer notieren. Buch im Regal finden. Mit dem Ausweis ausleihen.',
      ],
      choices: <String>[
        'Mit dem Ausweis ausleihen.',
        'Buch im Regal finden.',
        'Im Katalog suchen.',
        'Regalnummer notieren.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-experiment-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Ein Experiment durchführen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Material bereitstellen. Versuch durchführen. Genau beobachten. Ergebnis notieren.',
      ],
      choices: <String>[
        'Ergebnis notieren.',
        'Genau beobachten.',
        'Material bereitstellen.',
        'Versuch durchführen.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-apple-sauce-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Handlungsschritte sinnvoll.',
      prompt: 'Apfelmus kochen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Äpfel waschen. Äpfel schneiden. Stücke in den Topf geben. Weich kochen.',
      ],
      choices: <String>[
        'Weich kochen.',
        'Stücke in den Topf geben.',
        'Äpfel waschen.',
        'Äpfel schneiden.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-presentation-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Einen kurzen Vortrag vorbereiten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema wählen. Informationen sammeln. Stichpunkte ordnen. Vortrag üben.',
      ],
      choices: <String>[
        'Vortrag üben.',
        'Stichpunkte ordnen.',
        'Thema wählen.',
        'Informationen sammeln.',
      ],
    ),
  ];
}
