import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanTouchTaskCatalog {
  const GermanTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-build-sun',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Bild: ☀️',
      accessiblePrompt: 'Etwas am Himmel macht es tagsüber hell und warm.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Sonne'],
      choices: <String>['Son', 'ne', 'Som'],
    ),
    GermanTask(
      id: 'g1-build-flower',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Bild: 🌼',
      accessiblePrompt: 'Eine Pflanze mit bunten Blüten wächst im Garten.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Blume'],
      choices: <String>['Blu', 'me', 'mi'],
    ),
    GermanTask(
      id: 'g1-build-rain',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Bild: 🌧️',
      accessiblePrompt: 'Wasser fällt in Tropfen aus den Wolken.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Regen'],
      choices: <String>['Re', 'gen', 'gan'],
    ),
    GermanTask(
      id: 'g1-build-rabbit',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Bild: 🐇',
      accessiblePrompt: 'Ein Tier mit langen Ohren hoppelt über die Wiese.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Hase'],
      choices: <String>['Ha', 'se', 'si'],
    ),
    GermanTask(
      id: 'g2-plural-houses-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Haus – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Häuser'],
      choices: <String>['Häu', 'ser', 'Heu'],
    ),
    GermanTask(
      id: 'g2-plural-children-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Kind – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kinder'],
      choices: <String>['Kin', 'der', 'den'],
    ),
    GermanTask(
      id: 'g2-plural-books-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Buch – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bücher'],
      choices: <String>['Bü', 'cher', 'Bu'],
    ),
    GermanTask(
      id: 'g2-plural-mice-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Eine Maus – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Mäuse'],
      choices: <String>['Mäu', 'se', 'Mei'],
    ),
    GermanTask(
      id: 'g2-family-driver-build',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue ein Wort aus derselben Wortfamilie.',
      prompt: 'fahren → jemand, der fährt',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fahrer'],
      choices: <String>['Fahr', 'er', 'Fall'],
    ),
    GermanTask(
      id: 'g2-family-player-build',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue ein Wort aus derselben Wortfamilie.',
      prompt: 'spielen → jemand, der spielt',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Spieler'],
      choices: <String>['Spiel', 'er', 'Spül'],
    ),
    GermanTask(
      id: 'g3-spell-dog-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze das Verlängern und baue die Mehrzahl.',
      prompt: 'Hund → viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Hunde'],
      choices: <String>['Hun', 'de', 'te'],
    ),
    GermanTask(
      id: 'g3-spell-day-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze das Verlängern und baue die Mehrzahl.',
      prompt: 'Tag → viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tage'],
      choices: <String>['Ta', 'ge', 'ke'],
    ),
    GermanTask(
      id: 'g3-spell-cold-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze ein verwandtes Wort und baue die Lösung.',
      prompt: 'kalt → die …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kälte'],
      choices: <String>['Käl', 'te', 'ta'],
    ),
    GermanTask(
      id: 'g3-spell-tree-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze die Ableitung und baue die Mehrzahl.',
      prompt: 'Baum → viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bäume'],
      choices: <String>['Bäu', 'me', 'Beu'],
    ),
    GermanTask(
      id: 'g3-compound-umbrella-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze die beiden Wörter zu einem neuen Wort zusammen.',
      prompt: 'Regen + Schirm',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Regenschirm'],
      choices: <String>['Regen', 'schirm', 'schrank'],
    ),
    GermanTask(
      id: 'g3-compound-house-door-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze die beiden Wörter zu einem neuen Wort zusammen.',
      prompt: 'Haus + Tür',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Haustür'],
      choices: <String>['Haus', 'tür', 'tier'],
    ),
    GermanTask(
      id: 'g3-compound-schoolyard-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze die beiden Wörter zu einem neuen Wort zusammen.',
      prompt: 'Schule + Hof',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schulhof'],
      choices: <String>['Schul', 'hof', 'haus'],
    ),
    GermanTask(
      id: 'g3-compound-toothbrush-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze die beiden Wörter zu einem neuen Wort zusammen.',
      prompt: 'Zahn + Bürste',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Zahnbürste'],
      choices: <String>['Zahn', 'bürste', 'becher'],
    ),
    GermanTask(
      id: 'g4-spell-trip-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „fahren“ als verwandtes Wort und baue das Nomen.',
      prompt: 'die …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fahrt'],
      choices: <String>['Fahr', 't', 'd'],
    ),
    GermanTask(
      id: 'g4-spell-forest-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Wälder“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Wald'],
      choices: <String>['Wal', 'd', 't'],
    ),
    GermanTask(
      id: 'g4-spell-day-root-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Tage“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tag'],
      choices: <String>['Ta', 'g', 'k'],
    ),
    GermanTask(
      id: 'g4-spell-wheel-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Räder“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Rad'],
      choices: <String>['Ra', 'd', 't'],
    ),
  ];
}
