import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanSentenceConstituentTouchTaskCatalog {
  const GermanSentenceConstituentTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-constituents-when-means-school',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Womit?“',
      prompt: 'Am Morgen fährt Lea mit dem Bus zur Schule.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Am Morgen', 'mit dem Bus'],
      choices: <String>['Am Morgen', 'Lea', 'mit dem Bus', 'zur Schule'],
    ),
    GermanTask(
      id: 'g3-constituents-where-who-garden',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wo?“ und „Wer?“',
      prompt: 'Im Garten baut Tom mit seinem Vater eine Hütte.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Im Garten', 'Tom'],
      choices: <String>['Im Garten', 'Tom', 'mit seinem Vater', 'eine Hütte'],
    ),
    GermanTask(
      id: 'g3-constituents-when-whom-hospital',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Wen?“',
      prompt: 'Nach der Schule besucht Mia ihre Oma im Krankenhaus.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Nach der Schule', 'ihre Oma'],
      choices: <String>['Nach der Schule', 'Mia', 'ihre Oma', 'im Krankenhaus'],
    ),
    GermanTask(
      id: 'g3-constituents-when-where-to-table',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Wohin?“',
      prompt: 'Ben legt am Abend das Buch auf den Tisch.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['am Abend', 'auf den Tisch'],
      choices: <String>['Ben', 'am Abend', 'das Buch', 'auf den Tisch'],
    ),
    GermanTask(
      id: 'g3-constituents-why-where-rain',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Warum?“ und „Wo?“',
      prompt: 'Die Kinder spielen wegen des Regens in der Turnhalle.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['wegen des Regens', 'in der Turnhalle'],
      choices: <String>[
        'Die Kinder',
        'wegen des Regens',
        'in der Turnhalle',
        'spielen',
      ],
    ),
    GermanTask(
      id: 'g3-constituents-means-when-training',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Womit?“ und „Wann?“',
      prompt: 'Mit dem Fahrrad fährt Nora morgens zum Training.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Mit dem Fahrrad', 'morgens'],
      choices: <String>['Mit dem Fahrrad', 'Nora', 'morgens', 'zum Training'],
    ),
    GermanTask(
      id: 'g3-constituents-where-when-playground',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wo?“ und „Wann?“',
      prompt: 'Auf dem Spielplatz trifft Paul nachmittags seine Freunde.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Auf dem Spielplatz', 'nachmittags'],
      choices: <String>[
        'Auf dem Spielplatz',
        'Paul',
        'nachmittags',
        'seine Freunde',
      ],
    ),
    GermanTask(
      id: 'g3-constituents-whom-when-heft',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wem?“ und „Wann?“',
      prompt: 'Lina bringt ihrer Lehrerin heute das Heft.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['ihrer Lehrerin', 'heute'],
      choices: <String>['Lina', 'ihrer Lehrerin', 'heute', 'das Heft'],
    ),
    GermanTask(
      id: 'g3-constituents-when-where-dog',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Wo?“',
      prompt: 'Der Hund schläft nachts unter dem Tisch.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['nachts', 'unter dem Tisch'],
      choices: <String>['Der Hund', 'nachts', 'unter dem Tisch', 'schläft'],
    ),
    GermanTask(
      id: 'g3-constituents-when-means-berlin',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Womit?“',
      prompt: 'Am Samstag fährt die Familie mit dem Zug nach Berlin.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Am Samstag', 'mit dem Zug'],
      choices: <String>[
        'Am Samstag',
        'die Familie',
        'mit dem Zug',
        'nach Berlin',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-why-how-snow',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Warum?“ und „Wie?“',
      prompt: 'Wegen starken Schnees fährt der Bus heute besonders langsam.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Wegen starken Schnees', 'besonders langsam'],
      choices: <String>[
        'Wegen starken Schnees',
        'der Bus',
        'heute',
        'besonders langsam',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-when-whom-brother',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Wem?“',
      prompt: 'Nach dem Unterricht bringt Emma ihrem Bruder das Fahrrad.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Nach dem Unterricht', 'ihrem Bruder'],
      choices: <String>[
        'Nach dem Unterricht',
        'Emma',
        'ihrem Bruder',
        'das Fahrrad',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-wherefrom-means-wood',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Woher?“ und „Womit?“',
      prompt: 'Aus dem Schuppen holt Opa mit einer Schubkarre das Holz.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aus dem Schuppen', 'mit einer Schubkarre'],
      choices: <String>[
        'Aus dem Schuppen',
        'Opa',
        'mit einer Schubkarre',
        'das Holz',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-purpose-when-cake',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Wofür?“ und „Wann?“',
      prompt: 'Für das Schulfest backt Mia am Freitag einen Kuchen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Für das Schulfest', 'am Freitag'],
      choices: <String>[
        'Für das Schulfest',
        'Mia',
        'am Freitag',
        'einen Kuchen',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-when-how-fox',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Wie?“',
      prompt: 'Der Fuchs läuft in der Dämmerung leise durch den Garten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['in der Dämmerung', 'leise'],
      choices: <String>[
        'Der Fuchs',
        'in der Dämmerung',
        'leise',
        'durch den Garten',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-why-when-weimar',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Warum?“ und „Wann?“',
      prompt: 'Die Klasse fährt wegen des Projekts nächste Woche nach Weimar.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['wegen des Projekts', 'nächste Woche'],
      choices: <String>[
        'Die Klasse',
        'wegen des Projekts',
        'nächste Woche',
        'nach Weimar',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-how-where-to-glasses',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Wie?“ und „Wohin?“',
      prompt: 'Mit großer Vorsicht trägt Ben die Gläser ins Klassenzimmer.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Mit großer Vorsicht', 'ins Klassenzimmer'],
      choices: <String>[
        'Mit großer Vorsicht',
        'Ben',
        'die Gläser',
        'ins Klassenzimmer',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-wherefrom-when-station',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Woher?“ und „Wann?“',
      prompt: 'Vom Bahnhof geht Lea am Morgen zu Fuß zur Schule.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Vom Bahnhof', 'am Morgen'],
      choices: <String>[
        'Vom Bahnhof',
        'Lea',
        'am Morgen',
        'zu Fuß',
        'zur Schule',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-why-where-to-heat',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Warum?“ und „Wohin?“',
      prompt:
          'Wegen der Hitze stellt der Hausmeister die Getränke in den Schatten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Wegen der Hitze', 'in den Schatten'],
      choices: <String>[
        'Wegen der Hitze',
        'der Hausmeister',
        'die Getränke',
        'in den Schatten',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-when-wherefrom-library',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Woher?“',
      prompt: 'Am Nachmittag holt Nora aus der Bücherei ein Sachbuch.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Am Nachmittag', 'aus der Bücherei'],
      choices: <String>[
        'Am Nachmittag',
        'Nora',
        'aus der Bücherei',
        'ein Sachbuch',
      ],
    ),
  ];
}
