import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGrammarTouchTaskCatalog {
  const GermanGrammarTouchTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-mark-vowels-ampel',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Ampel',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['A', 'e'],
      choices: <String>['A', 'm', 'p', 'e', 'l'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-igel',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Igel',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['I', 'e'],
      choices: <String>['I', 'g', 'e', 'l'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-ofen',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Ofen',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['O', 'e'],
      choices: <String>['O', 'f', 'e', 'n'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-auto',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Auto',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['A', 'u', 'o'],
      choices: <String>['A', 'u', 't', 'o'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-dog-cat',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Der Hund jagt die Katze.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Hund', 'die Katze'],
      choices: <String>['Der Hund', 'jagt', 'die Katze'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-mouse-cheese',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Die Maus frisst den Käse.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Maus', 'den Käse'],
      choices: <String>['Die Maus', 'frisst', 'den Käse'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-child-book',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Ein Kind liest ein Buch.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Ein Kind', 'ein Buch'],
      choices: <String>['Ein Kind', 'liest', 'ein Buch'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-bird-branch',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Der Vogel sitzt auf dem Ast.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Vogel', 'dem Ast'],
      choices: <String>['Der Vogel', 'sitzt', 'auf', 'dem Ast'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-mia',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Mia malt und singt heute.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['malt', 'singt'],
      choices: <String>['Mia', 'malt', 'und', 'singt', 'heute'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-dog',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Der Hund rennt und springt.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['rennt', 'springt'],
      choices: <String>['Der Hund', 'rennt', 'und', 'springt'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-lea',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Lea liest und schreibt leise.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['liest', 'schreibt'],
      choices: <String>['Lea', 'liest', 'und', 'schreibt', 'leise'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-birds',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Die Vögel fliegen und zwitschern.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['fliegen', 'zwitschern'],
      choices: <String>['Die Vögel', 'fliegen', 'und', 'zwitschern'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-dog',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der kleine Hund trägt ein rotes Halsband.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['kleine', 'rotes'],
      choices: <String>[
        'Der',
        'kleine',
        'Hund',
        'trägt',
        'ein',
        'rotes',
        'Halsband',
      ],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-house',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Das alte Haus hat eine blaue Tür.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['alte', 'blaue'],
      choices: <String>['Das', 'alte', 'Haus', 'hat', 'eine', 'blaue', 'Tür'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-flower',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Die gelbe Blume wächst im großen Topf.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['gelbe', 'großen'],
      choices: <String>[
        'Die',
        'gelbe',
        'Blume',
        'wächst',
        'im',
        'großen',
        'Topf',
      ],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-bike',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Das schnelle Fahrrad hat einen schwarzen Sattel.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['schnelle', 'schwarzen'],
      choices: <String>[
        'Das',
        'schnelle',
        'Fahrrad',
        'hat',
        'einen',
        'schwarzen',
        'Sattel',
      ],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-children',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Die Kinder spielen heute auf dem Hof.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Kinder', 'spielen'],
      choices: <String>['Die Kinder', 'spielen', 'heute', 'auf dem Hof'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-cat',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Die Katze schläft auf dem Sofa.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Katze', 'schläft'],
      choices: <String>['Die Katze', 'schläft', 'auf dem Sofa'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-ben',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Ben öffnet vorsichtig das Fenster.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Ben', 'öffnet'],
      choices: <String>['Ben', 'öffnet', 'vorsichtig', 'das Fenster'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-birds',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Am Morgen singen die Vögel im Garten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['singen', 'die Vögel'],
      choices: <String>['Am Morgen', 'singen', 'die Vögel', 'im Garten'],
    ),
  ];
}
