import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGradeOneDiversityTaskCatalog {
  const GermanGradeOneDiversityTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-mark-vowels-maus',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Maus',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['a', 'u'],
      choices: <String>['M', 'a', 'u', 's'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-rose',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Rose',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['o', 'e'],
      choices: <String>['R', 'o', 's', 'e'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-kino',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Kino',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['i', 'o'],
      choices: <String>['K', 'i', 'n', 'o'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-uhr',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Uhr',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['U'],
      choices: <String>['U', 'h', 'r'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-opa',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Opa',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['O', 'a'],
      choices: <String>['O', 'p', 'a'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-brot',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Brot',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['o'],
      choices: <String>['B', 'r', 'o', 't'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-hund',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Hund',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['u'],
      choices: <String>['H', 'u', 'n', 'd'],
    ),
    GermanTask(
      id: 'g1-mark-vowels-eis',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere alle Selbstlaute im Wort.',
      prompt: 'Eis',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['E', 'i'],
      choices: <String>['E', 'i', 's'],
    ),
    GermanTask(
      id: 'g1-build-touch-haus',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Ein Gebäude, in dem Menschen wohnen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Haus'],
      choices: <String>['Hau', 's', 'ß'],
    ),
    GermanTask(
      id: 'g1-build-touch-tisch',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Ein Möbelstück mit einer Platte.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Tisch'],
      choices: <String>['Ti', 'sch', 'st'],
    ),
    GermanTask(
      id: 'g1-build-touch-mond',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Etwas Helles ist nachts am Himmel zu sehen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Mond'],
      choices: <String>['Mo', 'nd', 'nt'],
    ),
    GermanTask(
      id: 'g1-build-touch-fisch',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Ein Tier lebt im Wasser und hat Flossen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fisch'],
      choices: <String>['Fi', 'sch', 'ch'],
    ),
    GermanTask(
      id: 'g1-build-touch-lampe',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Sie macht einen Raum hell.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Lampe'],
      choices: <String>['Lam', 'pe', 'be'],
    ),
    GermanTask(
      id: 'g1-build-touch-katze',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Ein Haustier kann miauen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Katze'],
      choices: <String>['Kat', 'ze', 'se'],
    ),
    GermanTask(
      id: 'g1-build-touch-apfel',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Eine runde Frucht kann rot oder grün sein.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Apfel'],
      choices: <String>['Ap', 'fel', 'fer'],
    ),
    GermanTask(
      id: 'g1-build-touch-wolke',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Baue das Wort aus den passenden Bausteinen.',
      prompt: 'Sie ist am Himmel und kann Regen bringen.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Wolke'],
      choices: <String>['Wol', 'ke', 'ge'],
    ),
    GermanTask(
      id: 'g1-listen-mark-trip-bag',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Dinge, die Lea für den Ausflug einpackt.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Trinkflasche', 'Regenjacke'],
      choices: <String>['Trinkflasche', 'Regenjacke', 'Buch', 'Ball'],
      spokenText:
          'Für den Ausflug packt Lea eine Trinkflasche und eine Regenjacke ein. Das Buch und der Ball bleiben zu Hause.',
    ),
    GermanTask(
      id: 'g1-listen-mark-playground',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Dinge, die Ben auf dem Spielplatz macht.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['klettern', 'rutschen'],
      choices: <String>['klettern', 'rutschen', 'schaukeln', 'rennen'],
      spokenText:
          'Ben klettert zuerst auf die Leiter. Danach rutscht er die Rutsche hinunter.',
    ),
    GermanTask(
      id: 'g1-listen-mark-dog',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Informationen über den Hund.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['unter dem Tisch', 'roter Ball'],
      choices: <String>[
        'unter dem Tisch',
        'roter Ball',
        'auf dem Sofa',
        'blauer Ball',
      ],
      spokenText:
          'Der Hund schläft unter dem Tisch. Neben ihm liegt sein roter Ball.',
    ),
    GermanTask(
      id: 'g1-listen-mark-weather-change',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Wetterinformationen.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['morgens Nebel', 'mittags Sonne'],
      choices: <String>[
        'morgens Nebel',
        'mittags Sonne',
        'morgens Schnee',
        'mittags Regen',
      ],
      spokenText:
          'Am Morgen liegt Nebel über den Feldern. Mittags scheint die Sonne.',
    ),
    GermanTask(
      id: 'g1-listen-mark-lunchbox',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Dinge in der Brotdose.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Apfel', 'Joghurt'],
      choices: <String>['Apfel', 'Joghurt', 'Banane', 'Käse'],
      spokenText:
          'In Mias Brotdose liegen ein Apfel und ein Joghurt. Eine Banane ist heute nicht dabei.',
    ),
    GermanTask(
      id: 'g1-listen-mark-drawing',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Arbeitsaufträge.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['roten Stift nehmen', 'einen Kreis malen'],
      choices: <String>[
        'roten Stift nehmen',
        'einen Kreis malen',
        'blauen Stift nehmen',
        'ein Dreieck malen',
      ],
      spokenText:
          'Nimm den roten Stift. Male damit einen großen Kreis auf das Blatt.',
    ),
    GermanTask(
      id: 'g1-listen-mark-bus',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Informationen über Mias Busfahrt.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['acht Uhr', 'blaue Haltestelle'],
      choices: <String>[
        'acht Uhr',
        'blaue Haltestelle',
        'neun Uhr',
        'rote Haltestelle',
      ],
      spokenText:
          'Mias Bus fährt um acht Uhr. Sie wartet an der blauen Haltestelle.',
    ),
    GermanTask(
      id: 'g1-listen-mark-garden',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere die zwei Pflanzen, die Opa gießt.',
      prompt: 'Hörtext',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Tomaten', 'Erdbeeren'],
      choices: <String>['Tomaten', 'Erdbeeren', 'Kartoffeln', 'Bohnen'],
      spokenText:
          'Opa gießt im Garten die Tomaten und die Erdbeeren. Die Bohnen brauchen heute kein Wasser.',
    ),
    GermanTask(
      id: 'g1-talk-mark-interruption',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei gute Reaktionen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich entschuldige mich.',
        'Ich lasse das Kind zu Ende sprechen.',
      ],
      choices: <String>[
        'Ich entschuldige mich.',
        'Ich lasse das Kind zu Ende sprechen.',
        'Ich rede weiter.',
        'Ich wechsle das Thema.',
      ],
      spokenText:
          'Du hast ein anderes Kind aus Versehen unterbrochen, während es etwas erzählt hat.',
    ),
    GermanTask(
      id: 'g1-talk-mark-class-question',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei passende Reaktionen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich melde mich.',
        'Ich warte, bis ich dran bin.',
      ],
      choices: <String>[
        'Ich melde mich.',
        'Ich warte, bis ich dran bin.',
        'Ich rufe sofort.',
        'Ich rede gleichzeitig mit anderen.',
      ],
      spokenText:
          'Die Lehrerin stellt der ganzen Klasse eine Frage. Mehrere Kinder wissen die Antwort.',
    ),
    GermanTask(
      id: 'g1-talk-mark-mistake',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei hilfreiche Reaktionen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich erkläre ruhig meinen Gedanken.',
        'Ich mache dem Kind Mut.',
      ],
      choices: <String>[
        'Ich erkläre ruhig meinen Gedanken.',
        'Ich mache dem Kind Mut.',
        'Ich sage nur: falsch.',
        'Ich höre nicht mehr zu.',
      ],
      spokenText:
          'Dein Partner hat bei einer gemeinsamen Aufgabe eine andere Lösung als du.',
    ),
    GermanTask(
      id: 'g1-talk-mark-new-child',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei gute Reaktionen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich gebe dem Kind Zeit.',
        'Ich höre aufmerksam zu.',
      ],
      choices: <String>[
        'Ich gebe dem Kind Zeit.',
        'Ich höre aufmerksam zu.',
        'Ich spreche für das Kind.',
        'Ich wende mich ab.',
      ],
      spokenText:
          'Ein neues Kind möchte der Gruppe etwas erzählen und spricht noch sehr vorsichtig.',
    ),
    GermanTask(
      id: 'g1-talk-mark-noisy-group',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei Regeln, die helfen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Wir sprechen nacheinander.',
        'Wir sprechen leiser.',
      ],
      choices: <String>[
        'Wir sprechen nacheinander.',
        'Wir sprechen leiser.',
        'Alle reden gleichzeitig.',
        'Jede Person redet so laut wie möglich.',
      ],
      spokenText:
          'In einer Gruppenarbeit reden viele Kinder gleichzeitig. Niemand versteht die anderen gut.',
    ),
    GermanTask(
      id: 'g1-talk-mark-unclear-word',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei gute Reaktionen.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich frage freundlich nach.',
        'Ich höre mir die Erklärung an.',
      ],
      choices: <String>[
        'Ich frage freundlich nach.',
        'Ich höre mir die Erklärung an.',
        'Ich rate einfach.',
        'Ich wechsle sofort das Thema.',
      ],
      spokenText:
          'Ein anderes Kind benutzt ein Wort, das du noch nicht kennst.',
    ),
    GermanTask(
      id: 'g1-talk-mark-presentation-feedback',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei passende Reaktionen nach dem Vortrag.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Ich nenne etwas, das mir gefallen hat.',
        'Ich stelle eine freundliche Frage.',
      ],
      choices: <String>[
        'Ich nenne etwas, das mir gefallen hat.',
        'Ich stelle eine freundliche Frage.',
        'Ich rede mit meinem Nachbarn.',
        'Ich wechsle ohne Rückmeldung das Thema.',
      ],
      spokenText:
          'Ein Kind hat der Klasse gerade ein Tier vorgestellt. Danach dürfen die anderen reagieren.',
    ),
    GermanTask(
      id: 'g1-talk-mark-partner-turn',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Markiere zwei Regeln für das Partnergespräch.',
      prompt: 'Hör die Situation.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Wir wechseln uns ab.',
        'Wir hören einander zu.',
      ],
      choices: <String>[
        'Wir wechseln uns ab.',
        'Wir hören einander zu.',
        'Eine Person redet die ganze Zeit.',
        'Wir beginnen zwei Gespräche gleichzeitig.',
      ],
      spokenText:
          'Zwei Kinder sollen sich gegenseitig von ihrem Lieblingsspiel erzählen.',
    ),
  ];
}
