import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanTwoRoundCompletionTaskCatalog {
  const GermanTwoRoundCompletionTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-family-mark-run',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „renn-“.',
      prompt: 'Welche Wörter gehören wirklich zusammen?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['rennen', 'Rennbahn', 'Rennrad'],
      choices: <String>['rennen', 'Rennbahn', 'Rennrad', 'Rente', 'Rand'],
    ),
    GermanTask(
      id: 'g3-family-mark-bake',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „back-“.',
      prompt: 'Welche Wörter haben denselben Bedeutungskern?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['backen', 'Bäcker', 'Backofen'],
      choices: <String>['backen', 'Bäcker', 'Backofen', 'Becken', 'Bagger'],
    ),
    GermanTask(
      id: 'g3-family-mark-think',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „denk-“.',
      prompt: 'Welche Wörter sind miteinander verwandt?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['denken', 'Denker', 'Denkaufgabe'],
      choices: <String>['denken', 'Denker', 'Denkaufgabe', 'decken', 'danken'],
    ),
    GermanTask(
      id: 'g3-family-mark-ask',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „frag-“.',
      prompt: 'Welche Wörter gehören zu „fragen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['fragen', 'Frage', 'Fragesatz'],
      choices: <String>['fragen', 'Frage', 'Fragesatz', 'tragen', 'Frack'],
    ),
    GermanTask(
      id: 'g3-family-mark-learn-more',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „lern-“.',
      prompt: 'Welche Wörter tragen denselben Wortstamm?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['lernen', 'Lernweg', 'Lernziel'],
      choices: <String>['lernen', 'Lernweg', 'Lernziel', 'Lärm', 'leeren'],
    ),
    GermanTask(
      id: 'g3-family-mark-live-more',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „wohn-“.',
      prompt: 'Welche Wörter gehören zu „wohnen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['wohnen', 'Wohnort', 'Wohnzimmer'],
      choices: <String>['wohnen', 'Wohnort', 'Wohnzimmer', 'Wolle', 'Wonne'],
    ),
    GermanTask(
      id: 'g4-family-mark-speak',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „sprech-“.',
      prompt: 'Achte auf Stamm und Bedeutung.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['sprechen', 'Sprecher', 'Sprechstunde'],
      choices: <String>[
        'sprechen',
        'Sprecher',
        'Sprechstunde',
        'brechen',
        'Specht',
      ],
    ),
    GermanTask(
      id: 'g4-family-mark-run',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „lauf-“.',
      prompt: 'Welche Wörter gehören zu „laufen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['laufen', 'Läufer', 'Laufbahn'],
      choices: <String>['laufen', 'Läufer', 'Laufbahn', 'Laube', 'Haufen'],
    ),
    GermanTask(
      id: 'g4-family-mark-hope',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „hoff-“.',
      prompt: 'Welche Wörter sind wirklich miteinander verwandt?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['hoffen', 'Hoffnung', 'hoffnungsvoll'],
      choices: <String>['hoffen', 'Hoffnung', 'hoffnungsvoll', 'Hof', 'offen'],
    ),
    GermanTask(
      id: 'g4-family-mark-see',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „seh-“.',
      prompt: 'Finde Stamm und gemeinsamen Bedeutungskern.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['sehen', 'Sehtest', 'Sehschwäche'],
      choices: <String>['sehen', 'Sehtest', 'Sehschwäche', 'Sehne', 'Segen'],
    ),
    GermanTask(
      id: 'g4-family-mark-carry',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „trag-“.',
      prompt: 'Welche Wörter gehören zu „tragen“?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['tragen', 'Träger', 'Tragetasche'],
      choices: <String>['tragen', 'Träger', 'Tragetasche', 'fragen', 'träge'],
    ),
    GermanTask(
      id: 'g4-family-mark-calc',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere alle Wörter aus der Wortfamilie „rechn-/rechen-“.',
      prompt: 'Welche Wörter gehören wirklich zusammen?',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['rechnen', 'Rechner', 'Rechenweg'],
      choices: <String>['rechnen', 'Rechner', 'Rechenweg', 'Regen', 'Rechteck'],
    ),
    GermanTask(
      id: 'g4-compound-build-classroom-window',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'das Fenster des Klassenzimmers',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Klassenzimmerfenster'],
      choices: <String>['Klassen', 'zimmer', 'fenster', 'tür'],
    ),
    GermanTask(
      id: 'g4-compound-build-flashlight-battery',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'die Batterie einer Taschenlampe',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Taschenlampenbatterie'],
      choices: <String>['Taschen', 'lampen', 'batterie', 'licht'],
    ),
    GermanTask(
      id: 'g4-compound-build-bike-pump',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'eine Pumpe für Fahrradreifen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fahrradreifenpumpe'],
      choices: <String>['Fahrrad', 'reifen', 'pumpe', 'kette'],
    ),
    GermanTask(
      id: 'g4-compound-build-garden-tap',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus vier Teilen.',
      prompt: 'der Wasserhahn im Schulgarten',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schulgartenwasserhahn'],
      choices: <String>['Schul', 'garten', 'wasser', 'hahn', 'haus'],
    ),
    GermanTask(
      id: 'g4-compound-build-bookshelf-board',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus drei Teilen.',
      prompt: 'ein Brett aus einem Bücherregal',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bücherregalbrett'],
      choices: <String>['Bücher', 'regal', 'brett', 'tisch'],
    ),
    GermanTask(
      id: 'g4-compound-build-playground-equipment',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das zusammengesetzte Nomen aus vier Teilen.',
      prompt: 'ein Spielgerät auf dem Pausenhof',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Pausenhofspielgerät'],
      choices: <String>['Pausen', 'hof', 'spiel', 'gerät', 'platz'],
    ),
    GermanTask(
      id: 'g3-constituents-after-rain-sister',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wann?“ und „Mit wem?“',
      prompt: 'Nach dem Regen spielt Mia mit ihrer Schwester im Garten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Nach dem Regen', 'mit ihrer Schwester'],
      choices: <String>[
        'Nach dem Regen',
        'Mia',
        'mit ihrer Schwester',
        'im Garten',
      ],
    ),
    GermanTask(
      id: 'g3-constituents-joy-evening',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Satzglieder für „Wie?“ und „Wann?“',
      prompt: 'Mit großer Freude liest Ben am Abend das neue Buch.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Mit großer Freude', 'am Abend'],
      choices: <String>[
        'Mit großer Freude',
        'Ben',
        'am Abend',
        'das neue Buch',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-consideration-quiet',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Warum?“ und „Wie?“',
      prompt:
          'Aus Rücksicht auf die Nachbarn stellt Tom das Fahrrad leise in den Schuppen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aus Rücksicht auf die Nachbarn', 'leise'],
      choices: <String>[
        'Aus Rücksicht auf die Nachbarn',
        'Tom',
        'das Fahrrad',
        'leise',
        'in den Schuppen',
      ],
    ),
    GermanTask(
      id: 'g4-constituents-flashlight-outage',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Markiere die Satzglieder für „Womit?“ und „Wann?“',
      prompt:
          'Mit einer Taschenlampe sucht Lea nach dem Stromausfall im Keller nach der Sicherung.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Mit einer Taschenlampe',
        'nach dem Stromausfall',
      ],
      choices: <String>[
        'Mit einer Taschenlampe',
        'Lea',
        'nach dem Stromausfall',
        'im Keller',
        'nach der Sicherung',
      ],
    ),
  ];
}
