import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGradeTwoDiversityTaskCatalog {
  const GermanGradeTwoDiversityTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g2-mark-nouns-teacher-window',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Die Lehrerin öffnet das Fenster.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Lehrerin', 'das Fenster'],
      choices: <String>['Die Lehrerin', 'öffnet', 'das Fenster'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-boy-backpack',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Der Junge trägt den Ranzen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Junge', 'den Ranzen'],
      choices: <String>['Der Junge', 'trägt', 'den Ranzen'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-girl-apple',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Das Mädchen isst einen Apfel.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Das Mädchen', 'einen Apfel'],
      choices: <String>['Das Mädchen', 'isst', 'einen Apfel'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-father-bike',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Der Vater repariert das Fahrrad.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Vater', 'das Fahrrad'],
      choices: <String>['Der Vater', 'repariert', 'das Fahrrad'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-grandma-cake',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Die Oma backt einen Kuchen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Oma', 'einen Kuchen'],
      choices: <String>['Die Oma', 'backt', 'einen Kuchen'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-cat-chair',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Die Katze schläft auf dem Stuhl.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Die Katze', 'dem Stuhl'],
      choices: <String>['Die Katze', 'schläft', 'auf', 'dem Stuhl'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-child-ball',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Ein Kind wirft den Ball.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Ein Kind', 'den Ball'],
      choices: <String>['Ein Kind', 'wirft', 'den Ball'],
    ),
    GermanTask(
      id: 'g2-mark-nouns-neighbor-garden',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Nomen mit ihrem Artikel.',
      prompt: 'Der Nachbar gießt den Garten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Nachbar', 'den Garten'],
      choices: <String>['Der Nachbar', 'gießt', 'den Garten'],
    ),
    GermanTask(
      id: 'g2-plural-balls-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Ball – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bälle'],
      choices: <String>['Bäl', 'le', 'Bal'],
    ),
    GermanTask(
      id: 'g2-plural-hands-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Eine Hand – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Hände'],
      choices: <String>['Hän', 'de', 'Han'],
    ),
    GermanTask(
      id: 'g2-plural-apples-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Apfel – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Äpfel'],
      choices: <String>['Äp', 'fel', 'Ap'],
    ),
    GermanTask(
      id: 'g2-plural-gardens-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Garten – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Gärten'],
      choices: <String>['Gär', 'ten', 'Gar'],
    ),
    GermanTask(
      id: 'g2-plural-teeth-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Zahn – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Zähne'],
      choices: <String>['Zäh', 'ne', 'Zah'],
    ),
    GermanTask(
      id: 'g2-plural-birds-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Vogel – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Vögel'],
      choices: <String>['Vö', 'gel', 'Vo'],
    ),
    GermanTask(
      id: 'g2-plural-chairs-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Stuhl – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Stühle'],
      choices: <String>['Stüh', 'le', 'Stu'],
    ),
    GermanTask(
      id: 'g2-plural-brothers-build',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die Mehrzahl.',
      prompt: 'Ein Bruder – viele …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Brüder'],
      choices: <String>['Brü', 'der', 'Bru'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-cat',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Die junge Katze hat weiches Fell.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['junge', 'weiches'],
      choices: <String>['Die', 'junge', 'Katze', 'hat', 'weiches', 'Fell'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-cake',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der süße Kuchen liegt auf dem großen Teller.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['süße', 'großen'],
      choices: <String>[
        'Der',
        'süße',
        'Kuchen',
        'liegt',
        'auf',
        'dem',
        'großen',
        'Teller',
      ],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-scarf',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der lange Schal ist warm und weich.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['lange', 'warm', 'weich'],
      choices: <String>['Der', 'lange', 'Schal', 'ist', 'warm', 'und', 'weich'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-tree',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der hohe Baum trägt grüne Blätter.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['hohe', 'grüne'],
      choices: <String>['Der', 'hohe', 'Baum', 'trägt', 'grüne', 'Blätter'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-stone',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der runde Stein ist glatt und schwer.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['runde', 'glatt', 'schwer'],
      choices: <String>[
        'Der',
        'runde',
        'Stein',
        'ist',
        'glatt',
        'und',
        'schwer',
      ],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-rabbit',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Das kleine Kaninchen hat lange Ohren.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['kleine', 'lange'],
      choices: <String>['Das', 'kleine', 'Kaninchen', 'hat', 'lange', 'Ohren'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-backpack',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der schwere Ranzen hat breite Gurte.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['schwere', 'breite'],
      choices: <String>['Der', 'schwere', 'Ranzen', 'hat', 'breite', 'Gurte'],
    ),
    GermanTask(
      id: 'g2-mark-adjectives-river',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Adjektive im Satz.',
      prompt: 'Der breite Fluss führt kaltes Wasser.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['breite', 'kaltes'],
      choices: <String>['Der', 'breite', 'Fluss', 'führt', 'kaltes', 'Wasser'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-tom',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Tom rennt und lacht auf dem Hof.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['rennt', 'lacht'],
      choices: <String>['Tom', 'rennt', 'und', 'lacht', 'auf dem Hof'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-children',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Die Kinder bauen und malen zusammen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['bauen', 'malen'],
      choices: <String>['Die Kinder', 'bauen', 'und', 'malen', 'zusammen'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-grandma',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Oma kocht und backt heute.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['kocht', 'backt'],
      choices: <String>['Oma', 'kocht', 'und', 'backt', 'heute'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-cat',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Die Katze springt und klettert schnell.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['springt', 'klettert'],
      choices: <String>['Die Katze', 'springt', 'und', 'klettert', 'schnell'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-father',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Papa sägt und hämmert in der Werkstatt.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['sägt', 'hämmert'],
      choices: <String>['Papa', 'sägt', 'und', 'hämmert', 'in der Werkstatt'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-ducks',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Die Enten schwimmen und tauchen im Teich.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['schwimmen', 'tauchen'],
      choices: <String>['Die Enten', 'schwimmen', 'und', 'tauchen', 'im Teich'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-leo',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Leo öffnet und schließt die Tür.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['öffnet', 'schließt'],
      choices: <String>['Leo', 'öffnet', 'und', 'schließt', 'die Tür'],
    ),
    GermanTask(
      id: 'g2-mark-verbs-sara',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere alle Verben im Satz.',
      prompt: 'Sara rechnet und schreibt konzentriert.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['rechnet', 'schreibt'],
      choices: <String>['Sara', 'rechnet', 'und', 'schreibt', 'konzentriert'],
    ),
    GermanTask(
      id: 'g2-retell-order-sandcastle',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die drei Ereignisse der Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Mia füllt Sand in einen Eimer Sie stürzt den Eimer um Sie schmückt die Burg mit Muscheln',
      ],
      choices: <String>[
        'Mia füllt Sand in einen Eimer',
        'Sie stürzt den Eimer um',
        'Sie schmückt die Burg mit Muscheln',
      ],
      spokenText:
          'Mia füllt zuerst feuchten Sand in einen Eimer. Dann stürzt sie den Eimer vorsichtig um. Zum Schluss schmückt sie die Sandburg mit Muscheln.',
    ),
    GermanTask(
      id: 'g2-retell-order-glove',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die wichtigsten Ereignisse.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Ben vermisst seinen Handschuh Er sucht in der Garderobe Er findet ihn unter der Bank',
      ],
      choices: <String>[
        'Ben vermisst seinen Handschuh',
        'Er sucht in der Garderobe',
        'Er findet ihn unter der Bank',
      ],
      spokenText:
          'Ben bemerkt, dass ein Handschuh fehlt. Er sucht zuerst in der Garderobe. Schließlich entdeckt er den Handschuh unter seiner Bank.',
    ),
    GermanTask(
      id: 'g2-retell-order-cookies',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die Arbeitsschritte der Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Lea mischt den Teig Sie formt kleine Kekse Die Kekse kommen in den Ofen',
      ],
      choices: <String>[
        'Lea mischt den Teig',
        'Sie formt kleine Kekse',
        'Die Kekse kommen in den Ofen',
      ],
      spokenText:
          'Lea mischt zuerst den Teig. Danach formt sie daraus kleine Kekse. Zum Schluss schiebt sie das Blech in den Ofen.',
    ),
    GermanTask(
      id: 'g2-retell-order-kite',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die Ereignisse so, wie sie passiert sind.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Tom baut einen Drachen Er geht auf die Wiese Der Drachen steigt in die Luft',
      ],
      choices: <String>[
        'Tom baut einen Drachen',
        'Er geht auf die Wiese',
        'Der Drachen steigt in die Luft',
      ],
      spokenText:
          'Tom baut zu Hause einen bunten Drachen. Danach geht er mit ihm auf die Wiese. Dort steigt der Drachen im Wind hoch in die Luft.',
    ),
    GermanTask(
      id: 'g2-retell-order-seedling',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die drei Ereignisse der Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Nora pflanzt einen Samen Sie gießt die Erde Eine kleine Pflanze wächst',
      ],
      choices: <String>[
        'Nora pflanzt einen Samen',
        'Sie gießt die Erde',
        'Eine kleine Pflanze wächst',
      ],
      spokenText:
          'Nora pflanzt einen Samen in einen Topf. Jeden Tag gießt sie die Erde vorsichtig. Nach einigen Tagen wächst eine kleine Pflanze.',
    ),
    GermanTask(
      id: 'g2-retell-order-train',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die wichtigsten Ereignisse.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Die Familie kauft Fahrkarten Sie steigt in den Zug Sie kommt in Weimar an',
      ],
      choices: <String>[
        'Die Familie kauft Fahrkarten',
        'Sie steigt in den Zug',
        'Sie kommt in Weimar an',
      ],
      spokenText:
          'Die Familie kauft am Automaten Fahrkarten. Danach steigt sie in den Zug. Eine halbe Stunde später kommt sie in Weimar an.',
    ),
    GermanTask(
      id: 'g2-retell-order-library',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die Handlung der Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Mia sucht ein Tierbuch Sie leiht das Buch aus Sie liest zu Hause darin',
      ],
      choices: <String>[
        'Mia sucht ein Tierbuch',
        'Sie leiht das Buch aus',
        'Sie liest zu Hause darin',
      ],
      spokenText:
          'Mia sucht in der Bücherei ein Buch über Tiere. An der Theke leiht sie es aus. Zu Hause beginnt sie sofort darin zu lesen.',
    ),
    GermanTask(
      id: 'g2-retell-order-puddle',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Ordne die Ereignisse so, wie sie passiert sind.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Leo springt in eine Pfütze Seine Hose wird nass Er zieht zu Hause trockene Kleidung an',
      ],
      choices: <String>[
        'Leo springt in eine Pfütze',
        'Seine Hose wird nass',
        'Er zieht zu Hause trockene Kleidung an',
      ],
      spokenText:
          'Leo springt auf dem Heimweg in eine tiefe Pfütze. Dabei wird seine Hose ganz nass. Zu Hause zieht er sofort trockene Kleidung an.',
    ),
  ];
}
