import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGradeThreeDiversityTaskCatalog {
  const GermanGradeThreeDiversityTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-retell-order-library-book',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die wichtigsten Ereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Mila sucht ein Sachbuch Sie leiht das Buch aus Zu Hause beginnt sie zu lesen',
      ],
      choices: <String>[
        'Mila sucht ein Sachbuch',
        'Sie leiht das Buch aus',
        'Zu Hause beginnt sie zu lesen',
      ],
      spokenText:
          'Mila sucht in der Bücherei zuerst ein Sachbuch aus. Danach leiht sie es am Schalter aus. Zu Hause beginnt sie sofort zu lesen.',
    ),
    GermanTask(
      id: 'g3-retell-order-lost-dog',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Kernereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Ben bemerkt den offenen Gartenzaun Er sucht den Hund in der Nachbarschaft Er findet ihn am Spielplatz',
      ],
      choices: <String>[
        'Ben bemerkt den offenen Gartenzaun',
        'Er sucht den Hund in der Nachbarschaft',
        'Er findet ihn am Spielplatz',
      ],
      spokenText:
          'Ben bemerkt, dass der Gartenzaun offen steht und der Hund fehlt. Er sucht ihn in der Nachbarschaft. Am Spielplatz findet er ihn schließlich wieder.',
    ),
    GermanTask(
      id: 'g3-retell-order-cake',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die wichtigsten Ereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Nora mischt den Teig Der Kuchen backt im Ofen Sie verziert den abgekühlten Kuchen',
      ],
      choices: <String>[
        'Nora mischt den Teig',
        'Der Kuchen backt im Ofen',
        'Sie verziert den abgekühlten Kuchen',
      ],
      spokenText:
          'Nora mischt zuerst den Teig. Danach backt der Kuchen im Ofen. Als er abgekühlt ist, verziert sie ihn mit Obst.',
    ),
    GermanTask(
      id: 'g3-retell-order-bike-flat',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Kernereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Lea entdeckt den platten Reifen Sie holt die Luftpumpe Der Reifen wird wieder aufgepumpt',
      ],
      choices: <String>[
        'Lea entdeckt den platten Reifen',
        'Sie holt die Luftpumpe',
        'Der Reifen wird wieder aufgepumpt',
      ],
      spokenText:
          'Lea entdeckt vor der Fahrt einen platten Reifen. Sie holt die Luftpumpe aus dem Schuppen. Danach pumpt sie den Reifen wieder auf.',
    ),
    GermanTask(
      id: 'g3-retell-order-rainbow-test',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die wichtigsten Schritte der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Die Kinder stellen ein Wasserglas ans Fenster Sonnenlicht fällt durch das Glas Ein Farbstreifen erscheint an der Wand',
      ],
      choices: <String>[
        'Die Kinder stellen ein Wasserglas ans Fenster',
        'Sonnenlicht fällt durch das Glas',
        'Ein Farbstreifen erscheint an der Wand',
      ],
      spokenText:
          'Die Kinder stellen ein Wasserglas ans sonnige Fenster. Das Licht fällt durch das Wasser. Kurz darauf erscheint ein bunter Farbstreifen an der Wand.',
    ),
    GermanTask(
      id: 'g3-retell-order-school-trip',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Kernereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Die Klasse trifft sich am Bahnhof Sie fährt mit dem Zug ins Museum Am Nachmittag kehrt sie zurück',
      ],
      choices: <String>[
        'Die Klasse trifft sich am Bahnhof',
        'Sie fährt mit dem Zug ins Museum',
        'Am Nachmittag kehrt sie zurück',
      ],
      spokenText:
          'Am Morgen trifft sich die Klasse am Bahnhof. Gemeinsam fährt sie mit dem Zug ins Museum. Am Nachmittag kehrt die Gruppe wieder zurück.',
    ),
    GermanTask(
      id: 'g3-retell-order-garden',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Ereignisse so, wie sie passiert sind.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Tom lockert die Erde Er setzt die jungen Pflanzen ein Zum Schluss gießt er das Beet',
      ],
      choices: <String>[
        'Tom lockert die Erde',
        'Er setzt die jungen Pflanzen ein',
        'Zum Schluss gießt er das Beet',
      ],
      spokenText:
          'Tom lockert zuerst die Erde im Beet. Dann setzt er die jungen Pflanzen ein. Zum Schluss gießt er alles gründlich.',
    ),
    GermanTask(
      id: 'g3-retell-order-package',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Kernereignisse der gehörten Geschichte.',
      prompt: 'Hör die Geschichte.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Ein Paket wird geliefert Mia öffnet es vorsichtig Sie entdeckt ein Geburtstagsgeschenk',
      ],
      choices: <String>[
        'Ein Paket wird geliefert',
        'Mia öffnet es vorsichtig',
        'Sie entdeckt ein Geburtstagsgeschenk',
      ],
      spokenText:
          'Der Paketbote bringt am Nachmittag ein Paket. Mia öffnet es vorsichtig. Darin entdeckt sie ein Geburtstagsgeschenk von ihrer Tante.',
    ),
    GermanTask(
      id: 'g3-spell-hand-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Hände“ zum Prüfen und baue die Einzahl.',
      prompt: 'eine …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Hand'],
      choices: <String>['Han', 'd', 't'],
    ),
    GermanTask(
      id: 'g3-spell-korb-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Körbe“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Korb'],
      choices: <String>['Kor', 'b', 'p'],
    ),
    GermanTask(
      id: 'g3-spell-rad-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Räder“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Rad'],
      choices: <String>['Ra', 'd', 't'],
    ),
    GermanTask(
      id: 'g3-spell-berg-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Berge“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Berg'],
      choices: <String>['Ber', 'g', 'k'],
    ),
    GermanTask(
      id: 'g3-spell-bund-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Bünde“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bund'],
      choices: <String>['Bun', 'd', 't'],
    ),
    GermanTask(
      id: 'g3-spell-wald-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Wälder“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Wald'],
      choices: <String>['Wal', 'd', 't'],
    ),
    GermanTask(
      id: 'g3-spell-kalb-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Kälber“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kalb'],
      choices: <String>['Kal', 'b', 'p'],
    ),
    GermanTask(
      id: 'g3-spell-zug-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Nutze „Züge“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Zug'],
      choices: <String>['Zu', 'g', 'k'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-blatt',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Blume · Blatt · Blau · Blase',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Blase Blatt Blau Blume'],
      choices: <String>['Blume', 'Blatt', 'Blau', 'Blase'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-feder',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Fenster · Feld · Feder · Fell',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Feder Feld Fell Fenster'],
      choices: <String>['Fenster', 'Feld', 'Feder', 'Fell'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-hase',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Haus · Hase · Hand · Hafen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Hafen Hand Hase Haus'],
      choices: <String>['Haus', 'Hase', 'Hand', 'Hafen'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-kirche',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Kiste · Kind · Kino · Kirche',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Kind Kino Kirche Kiste'],
      choices: <String>['Kiste', 'Kind', 'Kino', 'Kirche'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-maus',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Mauer · Maus · Mappe · Mantel',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Mantel Mappe Mauer Maus'],
      choices: <String>['Mauer', 'Maus', 'Mappe', 'Mantel'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-reise',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Regen · Reise · Reh · Reifen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Regen Reh Reifen Reise'],
      choices: <String>['Regen', 'Reise', 'Reh', 'Reifen'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-stern',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Stein · Stern · Stelle · Steg',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Steg Stein Stelle Stern'],
      choices: <String>['Stein', 'Stern', 'Stelle', 'Steg'],
    ),
    GermanTask(
      id: 'g3-dictionary-order-tasche',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Tau · Tasse · Tafel · Tasche',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Tafel Tasche Tasse Tau'],
      choices: <String>['Tau', 'Tasse', 'Tafel', 'Tasche'],
    ),
    GermanTask(
      id: 'g3-compound-raincoat-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'eine Jacke für Regenwetter',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Regenjacke'],
      choices: <String>['Regen', 'jacke', 'schirm'],
    ),
    GermanTask(
      id: 'g3-compound-bookshelf-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'ein Regal für Bücher',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Bücherregal'],
      choices: <String>['Bücher', 'regal', 'tisch'],
    ),
    GermanTask(
      id: 'g3-compound-garden-fence-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'ein Zaun für den Garten',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Gartenzaun'],
      choices: <String>['Garten', 'zaun', 'haus'],
    ),
    GermanTask(
      id: 'g3-compound-sunglasses-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'eine Brille gegen Sonne',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Sonnenbrille'],
      choices: <String>['Sonnen', 'brille', 'schirm'],
    ),
    GermanTask(
      id: 'g3-compound-football-field-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'ein Platz für Fußball',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Fußballplatz'],
      choices: <String>['Fuß', 'ball', 'platz', 'feld'],
    ),
    GermanTask(
      id: 'g3-compound-kids-room-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'ein Zimmer für Kinder',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kinderzimmer'],
      choices: <String>['Kinder', 'zimmer', 'garten'],
    ),
    GermanTask(
      id: 'g3-compound-schoolbag-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'eine Tasche für die Schule',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schultasche'],
      choices: <String>['Schul', 'tasche', 'hof'],
    ),
    GermanTask(
      id: 'g3-compound-wintercoat-build',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue das zusammengesetzte Nomen.',
      prompt: 'eine Jacke für den Winter',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Winterjacke'],
      choices: <String>['Winter', 'jacke', 'mantel'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-mia',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Am Nachmittag liest Mia im Garten.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Mia', 'liest'],
      choices: <String>['Am Nachmittag', 'liest', 'Mia', 'im Garten'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-dog',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Der junge Hund wartet vor der Tür.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der junge Hund', 'wartet'],
      choices: <String>['Der junge Hund', 'wartet', 'vor der Tür'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-class',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Heute besucht die Klasse das Museum.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['die Klasse', 'besucht'],
      choices: <String>['Heute', 'besucht', 'die Klasse', 'das Museum'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-friends',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Noah und Lea sammeln Kastanien im Park.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Noah und Lea', 'sammeln'],
      choices: <String>['Noah und Lea', 'sammeln', 'Kastanien', 'im Park'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-grandpa',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Am Morgen gießt Opa die Blumen.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Opa', 'gießt'],
      choices: <String>['Am Morgen', 'gießt', 'Opa', 'die Blumen'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-bus',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Der Schulbus hält vor dem Gebäude.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Der Schulbus', 'hält'],
      choices: <String>['Der Schulbus', 'hält', 'vor dem Gebäude'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-sister',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Meine Schwester zeichnet ein Pferd.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Meine Schwester', 'zeichnet'],
      choices: <String>['Meine Schwester', 'zeichnet', 'ein Pferd'],
    ),
    GermanTask(
      id: 'g3-mark-subject-predicate-boys',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere Subjekt und Prädikat.',
      prompt: 'Auf dem Hof bauen zwei Jungen eine Burg.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['zwei Jungen', 'bauen'],
      choices: <String>['Auf dem Hof', 'bauen', 'zwei Jungen', 'eine Burg'],
    ),
    GermanTask(
      id: 'g3-tense-go-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute gehe ich. Gestern ___ ich.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['ging'],
      choices: <String>['g', 'ing', 'ang'],
    ),
    GermanTask(
      id: 'g3-tense-come-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute kommt Ben früh. Gestern ___ Ben früh.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['kam'],
      choices: <String>['ka', 'm', 'mm'],
    ),
    GermanTask(
      id: 'g3-tense-read-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute liest Mia. Gestern ___ Mia.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['las'],
      choices: <String>['la', 's', 'ß'],
    ),
    GermanTask(
      id: 'g3-tense-see-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute sieht Lea den Hund. Gestern ___ Lea den Hund.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['sah'],
      choices: <String>['sa', 'h', 'ch'],
    ),
    GermanTask(
      id: 'g3-tense-find-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute findet Tom den Schlüssel. Gestern ___ Tom den Schlüssel.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['fand'],
      choices: <String>['fan', 'd', 't'],
    ),
    GermanTask(
      id: 'g3-tense-run-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute läuft Nora schnell. Gestern ___ Nora schnell.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['lief'],
      choices: <String>['lie', 'f', 'v'],
    ),
    GermanTask(
      id: 'g3-tense-take-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute nimmt Ben den Bus. Gestern ___ Ben den Bus.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['nahm'],
      choices: <String>['nah', 'm', 'mm'],
    ),
    GermanTask(
      id: 'g3-tense-write-past-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Baue die Verbform in der Vergangenheit.',
      prompt: 'Heute schreibt Mia einen Brief. Gestern ___ Mia einen Brief.',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['schrieb'],
      choices: <String>['schrie', 'b', 'p'],
    ),
    GermanTask(
      id: 'g3-inference-evidence-school-start',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Markiere alle Hinweise darauf, dass der Unterricht gleich beginnt.',
      prompt:
          'Die Kinder sitzen an ihren Plätzen. Die Hefte liegen offen. Die Lehrerin schreibt das Datum an die Tafel. Vor dem Fenster fährt ein Auto vorbei.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Die Kinder sitzen an ihren Plätzen.',
        'Die Hefte liegen offen.',
        'Die Lehrerin schreibt das Datum an die Tafel.',
      ],
      choices: <String>[
        'Die Kinder sitzen an ihren Plätzen.',
        'Die Hefte liegen offen.',
        'Die Lehrerin schreibt das Datum an die Tafel.',
        'Vor dem Fenster fährt ein Auto vorbei.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-hot-day',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere alle Hinweise darauf, dass es sehr warm ist.',
      prompt:
          'Die Fenster stehen weit offen. Viele Kinder trinken Wasser. Im Hof suchen alle den Schatten. Auf dem Tisch liegt ein roter Ordner.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Die Fenster stehen weit offen.',
        'Viele Kinder trinken Wasser.',
        'Im Hof suchen alle den Schatten.',
      ],
      choices: <String>[
        'Die Fenster stehen weit offen.',
        'Viele Kinder trinken Wasser.',
        'Im Hof suchen alle den Schatten.',
        'Auf dem Tisch liegt ein roter Ordner.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-lost-item',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Hinweise darauf, dass Lea etwas sucht.',
      prompt:
          'Lea schaut unter den Tisch. Danach öffnet sie alle Taschen ihres Ranzens. Sie fragt Ben, ob er ihren Schlüssel gesehen hat. An der Wand hängt ein Kalender.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Lea schaut unter den Tisch.',
        'Danach öffnet sie alle Taschen ihres Ranzens.',
        'Sie fragt Ben, ob er ihren Schlüssel gesehen hat.',
      ],
      choices: <String>[
        'Lea schaut unter den Tisch.',
        'Danach öffnet sie alle Taschen ihres Ranzens.',
        'Sie fragt Ben, ob er ihren Schlüssel gesehen hat.',
        'An der Wand hängt ein Kalender.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-bus-wait',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Markiere alle Hinweise darauf, dass die Kinder auf den Bus warten.',
      prompt:
          'Die Kinder stehen an der Haltestelle. Mehrere schauen die Straße hinunter. Ben prüft den Fahrplan. Neben der Bank wächst Gras.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Die Kinder stehen an der Haltestelle.',
        'Mehrere schauen die Straße hinunter.',
        'Ben prüft den Fahrplan.',
      ],
      choices: <String>[
        'Die Kinder stehen an der Haltestelle.',
        'Mehrere schauen die Straße hinunter.',
        'Ben prüft den Fahrplan.',
        'Neben der Bank wächst Gras.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-baking',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Hinweise darauf, dass jemand backt.',
      prompt:
          'Mehl liegt auf der Arbeitsplatte. Der Ofen ist vorgeheizt. In einer Schüssel wird Teig gerührt. Auf dem Fensterbrett steht eine Pflanze.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Mehl liegt auf der Arbeitsplatte.',
        'Der Ofen ist vorgeheizt.',
        'In einer Schüssel wird Teig gerührt.',
      ],
      choices: <String>[
        'Mehl liegt auf der Arbeitsplatte.',
        'Der Ofen ist vorgeheizt.',
        'In einer Schüssel wird Teig gerührt.',
        'Auf dem Fensterbrett steht eine Pflanze.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-night',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Hinweise darauf, dass es Nacht ist.',
      prompt:
          'Am Himmel sind Sterne zu sehen. In vielen Häusern brennen Lampen. Die Straße ist fast leer. Auf dem Gehweg liegt ein Blatt.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Am Himmel sind Sterne zu sehen.',
        'In vielen Häusern brennen Lampen.',
        'Die Straße ist fast leer.',
      ],
      choices: <String>[
        'Am Himmel sind Sterne zu sehen.',
        'In vielen Häusern brennen Lampen.',
        'Die Straße ist fast leer.',
        'Auf dem Gehweg liegt ein Blatt.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-moving',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Markiere die Hinweise darauf, dass eine Familie umzieht.',
      prompt:
          'Im Flur stehen viele beschriftete Kartons. Ein Schrank ist bereits leer. Vor dem Haus steht ein großer Transporter. Die Klingel ist weiß.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Im Flur stehen viele beschriftete Kartons.',
        'Ein Schrank ist bereits leer.',
        'Vor dem Haus steht ein großer Transporter.',
      ],
      choices: <String>[
        'Im Flur stehen viele beschriftete Kartons.',
        'Ein Schrank ist bereits leer.',
        'Vor dem Haus steht ein großer Transporter.',
        'Die Klingel ist weiß.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-evidence-sports',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Markiere die Hinweise darauf, dass gleich Sport stattfindet.',
      prompt:
          'Die Kinder tragen Turnschuhe. In der Halle liegen Bälle bereit. Die Lehrerin stellt Hütchen auf. Auf der Fensterbank steht eine Trinkflasche.',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>[
        'Die Kinder tragen Turnschuhe.',
        'In der Halle liegen Bälle bereit.',
        'Die Lehrerin stellt Hütchen auf.',
      ],
      choices: <String>[
        'Die Kinder tragen Turnschuhe.',
        'In der Halle liegen Bälle bereit.',
        'Die Lehrerin stellt Hütchen auf.',
        'Auf der Fensterbank steht eine Trinkflasche.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-tea-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Tee zubereiten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Wasser erhitzen. Teebeutel in die Tasse legen. Heißes Wasser eingießen. Tee ziehen lassen.',
      ],
      choices: <String>[
        'Tee ziehen lassen.',
        'Wasser erhitzen.',
        'Heißes Wasser eingießen.',
        'Teebeutel in die Tasse legen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-letter-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Einen Brief verschicken',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Brief schreiben. Umschlag beschriften. Brief hineinlegen. Briefmarke aufkleben.',
      ],
      choices: <String>[
        'Briefmarke aufkleben.',
        'Brief hineinlegen.',
        'Brief schreiben.',
        'Umschlag beschriften.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-seed-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Kresse säen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Schale vorbereiten. Samen verteilen. Samen befeuchten. Schale ans Licht stellen.',
      ],
      choices: <String>[
        'Samen befeuchten.',
        'Schale ans Licht stellen.',
        'Schale vorbereiten.',
        'Samen verteilen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-photo-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Foto für ein Plakat vorbereiten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Motiv auswählen. Foto aufnehmen. Passenden Ausschnitt wählen. Foto auf dem Plakat platzieren.',
      ],
      choices: <String>[
        'Foto aufnehmen.',
        'Foto auf dem Plakat platzieren.',
        'Motiv auswählen.',
        'Passenden Ausschnitt wählen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-salad-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Einen Tomatensalat machen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Tomaten waschen. Tomaten schneiden. Alles in eine Schüssel geben. Salat würzen.',
      ],
      choices: <String>[
        'Salat würzen.',
        'Tomaten schneiden.',
        'Tomaten waschen.',
        'Alles in eine Schüssel geben.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-bag-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Den Schulranzen für morgen packen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Stundenplan prüfen. Benötigte Hefte holen. Mäppchen kontrollieren. Alles in den Ranzen packen.',
      ],
      choices: <String>[
        'Alles in den Ranzen packen.',
        'Mäppchen kontrollieren.',
        'Stundenplan prüfen.',
        'Benötigte Hefte holen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-bike-clean-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Fahrrad reinigen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Groben Schmutz abbürsten. Fahrrad mit Wasser abspülen. Rahmen abwischen. Fahrrad trocknen lassen.',
      ],
      choices: <String>[
        'Fahrrad trocknen lassen.',
        'Rahmen abwischen.',
        'Groben Schmutz abbürsten.',
        'Fahrrad mit Wasser abspülen.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-poster-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Lernplakat gestalten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema festlegen. Wichtige Informationen auswählen. Überschrift schreiben. Bilder und Text anordnen.',
      ],
      choices: <String>[
        'Bilder und Text anordnen.',
        'Thema festlegen.',
        'Überschrift schreiben.',
        'Wichtige Informationen auswählen.',
      ],
    ),
    GermanTask(
      id: 'g3-present-order-volcano',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Ordne die Teile der Präsentation in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema nennen Entstehung erklären Beispiel zeigen',
      ],
      choices: <String>[
        'Beispiel zeigen',
        'Thema nennen',
        'Entstehung erklären',
      ],
      spokenText:
          'Heute geht es um Vulkane. Zuerst erkläre ich, wie ein Vulkan entsteht. Danach zeige ich euch ein bekanntes Beispiel.',
    ),
    GermanTask(
      id: 'g3-present-order-water-cycle',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Präsentationsteile in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Frage stellen Kreislauf erklären Ergebnis zusammenfassen',
      ],
      choices: <String>[
        'Ergebnis zusammenfassen',
        'Frage stellen',
        'Kreislauf erklären',
      ],
      spokenText:
          'Wie kommt Regen eigentlich wieder in die Wolken? Mit dieser Frage beginne ich. Danach erkläre ich den Wasserkreislauf. Zum Schluss fasse ich den wichtigsten Gedanken zusammen.',
    ),
    GermanTask(
      id: 'g3-present-order-animal',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Ordne die Teile der Präsentation in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Tier vorstellen Lebensraum erklären Besonderheit nennen',
      ],
      choices: <String>[
        'Besonderheit nennen',
        'Tier vorstellen',
        'Lebensraum erklären',
      ],
      spokenText:
          'Ich stelle euch heute den Rotfuchs vor. Danach erkläre ich, wo er lebt. Am Ende nenne ich eine besondere Fähigkeit des Fuchses.',
    ),
    GermanTask(
      id: 'g3-present-order-city',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Präsentationsteile in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Ort nennen zwei Sehenswürdigkeiten erklären Empfehlung geben',
      ],
      choices: <String>[
        'Empfehlung geben',
        'Ort nennen',
        'zwei Sehenswürdigkeiten erklären',
      ],
      spokenText:
          'Heute stelle ich euch Erfurt vor. Zuerst zeige ich zwei bekannte Sehenswürdigkeiten. Zum Schluss sage ich, welchen Ort ich besonders empfehlen würde.',
    ),
    GermanTask(
      id: 'g3-present-order-invention',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Präsentationsteile in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Erfindung nennen Nutzen erklären Funktionsweise zeigen',
      ],
      choices: <String>[
        'Funktionsweise zeigen',
        'Erfindung nennen',
        'Nutzen erklären',
      ],
      spokenText:
          'Ich stelle euch heute eine Erfindung vor. Zuerst erkläre ich, wofür sie nützlich ist. Danach zeige ich, wie sie funktioniert.',
    ),
    GermanTask(
      id: 'g3-present-order-solar',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Präsentationsteile in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema ankündigen Funktionsweise erklären Vorteil nennen',
      ],
      choices: <String>[
        'Vorteil nennen',
        'Thema ankündigen',
        'Funktionsweise erklären',
      ],
      spokenText:
          'Heute geht es um Solaranlagen. Danach erkläre ich, wie Sonnenlicht zu Strom wird. Zum Schluss nenne ich einen wichtigen Vorteil.',
    ),
    GermanTask(
      id: 'g3-present-order-book-character',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction:
          'Ordne die Teile der Präsentation in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Figur vorstellen wichtige Eigenschaft erklären Textstelle nennen',
      ],
      choices: <String>[
        'Textstelle nennen',
        'Figur vorstellen',
        'wichtige Eigenschaft erklären',
      ],
      spokenText:
          'Ich stelle euch zuerst meine Lieblingsfigur vor. Danach erkläre ich ihre wichtigste Eigenschaft. Zum Schluss nenne ich eine passende Stelle aus dem Buch.',
    ),
    GermanTask(
      id: 'g3-present-order-project-result',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Ordne die Präsentationsteile in der gehörten Reihenfolge.',
      prompt: 'Hör den kurzen Vortrag.',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Aufgabe nennen Vorgehen erklären Ergebnis bewerten',
      ],
      choices: <String>[
        'Ergebnis bewerten',
        'Aufgabe nennen',
        'Vorgehen erklären',
      ],
      spokenText:
          'Zuerst sage ich, welche Aufgabe unsere Gruppe hatte. Danach erkläre ich unser Vorgehen. Am Ende bewerte ich, wie gut unser Ergebnis geworden ist.',
    ),
  ];
}
