import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanUpperPrimaryExpansionTaskCatalog {
  const GermanUpperPrimaryExpansionTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g3-spelling-strategy-korb',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches Wort hilft dir bei der Endung von „Korb“?',
      prompt: 'Du möchtest prüfen, ob du am Ende b oder p schreibst.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Körbe'],
      choices: <String>['Körbe', 'Korken', 'Kopf'],
    ),
    GermanTask(
      id: 'g3-spelling-strategy-baeume',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches verwandte Wort hilft dir bei „Bäume“?',
      prompt: 'Prüfe, warum „Bäume“ mit äu geschrieben wird.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Baum'],
      choices: <String>['Baum', 'Bein', 'Blume'],
    ),
    GermanTask(
      id: 'g3-spelling-strategy-rad',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Strategie hilft bei „Rad“?',
      prompt: 'Du bist bei d oder t am Wortende unsicher.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Verlängern: Räder'],
      choices: <String>[
        'Verlängern: Räder',
        'Den Artikel wechseln',
        'Das Wort schneller sprechen',
      ],
    ),
    GermanTask(
      id: 'g3-dictionary-band',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches Wort findest du im Wörterbuch zuerst?',
      prompt: 'Bank · Band · Bart',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Band'],
      choices: <String>['Bank', 'Band', 'Bart'],
    ),
    GermanTask(
      id: 'g3-dictionary-ging',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Unter welcher Grundform suchst du „ging“?',
      prompt: 'Finde die passende Wörterbuchform.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['gehen'],
      choices: <String>['gehen', 'ging', 'Gang'],
    ),
    GermanTask(
      id: 'g3-dictionary-schoensten',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Unter welcher Grundform suchst du „am schönsten“?',
      prompt: 'Denke an die Grundform des Adjektivs.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['schön'],
      choices: <String>['schön', 'Schönheit', 'schönsten'],
    ),
    GermanTask(
      id: 'g3-compound-garden-fence',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Aus welchen Wörtern besteht „Gartenzaun“?',
      prompt: 'Zerlege das zusammengesetzte Nomen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Garten + Zaun'],
      choices: <String>['Garten + Zaun', 'Gabel + Zaun', 'Garten + Zahn'],
    ),
    GermanTask(
      id: 'g3-compound-sunglasses',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche zwei Wörter bilden „Sonnenbrille“?',
      prompt: 'Finde die beiden bedeutungstragenden Teile.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Sonne + Brille'],
      choices: <String>['Sonne + Brille', 'Sohn + Brille', 'Sonne + Bild'],
    ),
    GermanTask(
      id: 'g3-compound-bookshelf',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welches zusammengesetzte Wort passt?',
      prompt: 'ein Regal für Bücher',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Bücherregal'],
      choices: <String>['Bücherregal', 'Küchenregal', 'Schuhregal'],
    ),
    GermanTask(
      id: 'g3-subject-sister',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist das Subjekt?',
      prompt: 'Am Abend liest meine Schwester ein Buch.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['meine Schwester'],
      choices: <String>['meine Schwester', 'liest', 'Am Abend'],
    ),
    GermanTask(
      id: 'g3-predicate-birds',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist das Prädikat?',
      prompt: 'Die Vögel fliegen über den See.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['fliegen'],
      choices: <String>['fliegen', 'Die Vögel', 'über den See'],
    ),
    GermanTask(
      id: 'g3-subject-friends',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Wer oder was sammelt Kastanien?',
      prompt: 'Noah und seine Freundin sammeln Kastanien.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Noah und seine Freundin'],
      choices: <String>['Noah und seine Freundin', 'sammeln', 'Kastanien'],
    ),
    GermanTask(
      id: 'g3-constituent-where-playground',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Wo?“',
      prompt: 'Auf dem Spielplatz trifft Ben seine Freunde.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Auf dem Spielplatz'],
      choices: <String>['Auf dem Spielplatz', 'Ben', 'seine Freunde'],
    ),
    GermanTask(
      id: 'g3-constituent-when-afternoon',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Wann?“',
      prompt: 'Am Nachmittag besucht Mia ihre Oma.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Am Nachmittag'],
      choices: <String>['Am Nachmittag', 'Mia', 'ihre Oma'],
    ),
    GermanTask(
      id: 'g3-constituent-where-to-library',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Satzteil antwortet auf „Wohin?“',
      prompt: 'Nach der Schule geht Lina in die Bücherei.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['in die Bücherei'],
      choices: <String>['in die Bücherei', 'Nach der Schule', 'Lina'],
    ),
    GermanTask(
      id: 'g3-tense-read',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Verbform passt zu „gestern“?',
      prompt: 'Heute liest Mia. Gestern ___ Mia.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['las'],
      choices: <String>['las', 'liest', 'lesen'],
    ),
    GermanTask(
      id: 'g3-tense-come',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Setze den Satz in die Vergangenheit.',
      prompt: 'Heute kommt Ben früh. Gestern ___ Ben früh.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['kam'],
      choices: <String>['kam', 'kommt', 'kommen'],
    ),
    GermanTask(
      id: 'g3-tense-present',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'In welcher Zeitform steht der Satz?',
      prompt: 'Die Kinder bauen eine Sandburg.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Gegenwart'],
      choices: <String>['Gegenwart', 'Vergangenheit', 'Zukunft'],
    ),
    GermanTask(
      id: 'g3-inference-sleep',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was kannst du aus dem Text schließen?',
      prompt:
          'Im Zimmer ist es dunkel. Paul liegt im Bett und schnarcht leise.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Paul schläft.'],
      choices: <String>[
        'Paul schläft.',
        'Paul macht Hausaufgaben.',
        'Paul frühstückt.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-raincoat',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Schlussfolgerung passt?',
      prompt:
          'Nora kommt mit nasser Regenjacke und tropfendem Schirm ins Haus.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Draußen regnet es.'],
      choices: <String>[
        'Draußen regnet es.',
        'Draußen ist es trocken.',
        'Nora war schwimmen.',
      ],
    ),
    GermanTask(
      id: 'g3-inference-lunchbox',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was ist wahrscheinlich passiert?',
      prompt:
          'In der Brotdose liegen nur noch Krümel. Emil wischt sich den Mund ab.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Emil hat sein Essen aufgegessen.'],
      choices: <String>[
        'Emil hat sein Essen aufgegessen.',
        'Emil hat noch gar nichts gegessen.',
        'Emil hat die Brotdose gerade gekauft.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-bike',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was geschieht zuerst?',
      prompt:
          'Leo prüft den Reifen. Dann pumpt er Luft hinein. Zum Schluss fährt er los.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Leo prüft den Reifen.'],
      choices: <String>[
        'Leo prüft den Reifen.',
        'Leo pumpt Luft hinein.',
        'Leo fährt los.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-cocoa',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was passiert nach dem Erwärmen?',
      prompt:
          'Zuerst erwärmt Lina die Milch. Danach rührt sie Kakao ein. Anschließend gießt sie alles in eine Tasse.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Sie rührt Kakao ein.'],
      choices: <String>[
        'Sie rührt Kakao ein.',
        'Sie erwärmt die Milch.',
        'Sie trinkt Wasser.',
      ],
    ),
    GermanTask(
      id: 'g3-sequence-homework',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was geschieht zuletzt?',
      prompt:
          'Amir holt sein Heft heraus. Dann löst er die Aufgaben. Danach packt er das Heft wieder ein.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Amir packt das Heft wieder ein.'],
      choices: <String>[
        'Amir packt das Heft wieder ein.',
        'Amir holt sein Heft heraus.',
        'Amir löst die Aufgaben.',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-water',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Überschrift fasst den Text am besten zusammen?',
      prompt:
          'Beim Zähneputzen läuft oft unnötig Wasser. Wer den Hahn zwischendurch schließt, kann jeden Tag viele Liter Wasser sparen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Beim Zähneputzen Wasser sparen'],
      choices: <String>[
        'Beim Zähneputzen Wasser sparen',
        'Wie Zahnpasta hergestellt wird',
        'Warum Wasser blau aussieht',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-hedgehog',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was ist die Kernaussage?',
      prompt:
          'Igel finden in Laubhaufen Schutz für den Winter. Deshalb sollte im Herbst nicht jedes Blatt aus dem Garten entfernt werden.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Laubhaufen können Igeln im Winter helfen.'],
      choices: <String>[
        'Laubhaufen können Igeln im Winter helfen.',
        'Igel fressen im Winter nur Blätter.',
        'Im Herbst wachsen keine Pflanzen mehr.',
      ],
    ),
    GermanTask(
      id: 'g4-mainidea-reading',
      competencyId: GermanCompetencyId.textMainIdea,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Zusammenfassung passt am besten?',
      prompt:
          'Wer regelmäßig liest, begegnet vielen neuen Wörtern und Geschichten. Mit der Zeit fällt es oft leichter, längere Texte zu verstehen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Regelmäßiges Lesen kann das Textverständnis stärken.',
      ],
      choices: <String>[
        'Regelmäßiges Lesen kann das Textverständnis stärken.',
        'Lange Texte sind immer langweilig.',
        'Neue Wörter sollte man vermeiden.',
      ],
    ),
    GermanTask(
      id: 'g4-connect-contrast',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Verbindungswort passt?',
      prompt: 'Es regnet stark, ___ die Kinder spielen draußen weiter.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['aber'],
      choices: <String>['aber', 'weil', 'deshalb'],
    ),
    GermanTask(
      id: 'g4-connect-reason',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Wort verbindet Ursache und Folge passend?',
      prompt: 'Der Bus kommt später. ___ wartet Mila noch an der Haltestelle.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Deshalb'],
      choices: <String>['Deshalb', 'Trotzdem', 'Bevor'],
    ),
    GermanTask(
      id: 'g4-connect-time',
      competencyId: GermanCompetencyId.sentenceConnections,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches Wort zeigt, was zuerst passiert?',
      prompt: '___ Ben die Tür öffnet, klingelt er.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Bevor'],
      choices: <String>['Bevor', 'Weil', 'Trotzdem'],
    ),
    GermanTask(
      id: 'g4-revision-specific-verb',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Fassung verwendet ein genaueres Verb?',
      prompt: 'Der Vogel machte sich schnell in die Luft.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Der Vogel flog schnell davon.'],
      choices: <String>[
        'Der Vogel flog schnell davon.',
        'Der Vogel machte etwas.',
        'Der Vogel war da.',
      ],
    ),
    GermanTask(
      id: 'g4-revision-pronoun',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Fassung klingt flüssiger?',
      prompt: 'Mia nimmt Mias Rucksack. Mia geht mit Mias Rucksack los.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Mia nimmt ihren Rucksack und geht damit los.'],
      choices: <String>[
        'Mia nimmt ihren Rucksack und geht damit los.',
        'Mia nimmt Mias Rucksack. Mia geht mit Mias Rucksack los.',
        'Mia Rucksack los.',
      ],
    ),
    GermanTask(
      id: 'g4-revision-logical-order',
      competencyId: GermanCompetencyId.textRevision,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Fassung hat eine sinnvolle Reihenfolge?',
      prompt: 'Es geht um das Backen eines Kuchens.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Zuerst wird der Teig gerührt. Danach kommt er in die Form. Zum Schluss wird der Kuchen gebacken.',
      ],
      choices: <String>[
        'Zuerst wird der Teig gerührt. Danach kommt er in die Form. Zum Schluss wird der Kuchen gebacken.',
        'Zuerst wird der Kuchen gebacken. Danach wird der Teig gerührt.',
        'Form, Kuchen, Teig.',
      ],
    ),
    GermanTask(
      id: 'g4-listen-mainidea-weather',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Hör zu. Was ist die wichtigste Information?',
      prompt: 'Tippe auf Anhören und wähle die Kernaussage.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Der Wandertag wird wegen des Wetters verschoben.',
      ],
      choices: <String>[
        'Der Wandertag wird wegen des Wetters verschoben.',
        'Die Klasse bekommt neue Wanderschuhe.',
        'Der Unterricht beginnt morgen später.',
      ],
      spokenText:
          'Für morgen ist ein starkes Gewitter angekündigt. Deshalb findet der Wandertag nicht morgen, sondern am kommenden Dienstag statt. Der Unterricht läuft morgen nach Plan.',
    ),
    GermanTask(
      id: 'g4-listen-mainidea-museum',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Worum geht es hauptsächlich?',
      prompt: 'Hör die Ansage und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Die Gruppe soll sich um elf Uhr am Museumseingang treffen.',
      ],
      choices: <String>[
        'Die Gruppe soll sich um elf Uhr am Museumseingang treffen.',
        'Das Museum verkauft keine Eintrittskarten mehr.',
        'Die Gruppe soll sofort nach Hause fahren.',
      ],
      spokenText:
          'Nach der Führung habt ihr noch zwanzig Minuten Zeit im Museumsshop. Bitte seid spätestens um elf Uhr wieder gemeinsam am Haupteingang.',
    ),
    GermanTask(
      id: 'g4-listen-mainidea-homework',
      competencyId: GermanCompetencyId.listeningMainIdeas,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Aussage fasst den Auftrag zusammen?',
      prompt: 'Hör genau zu und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Bis Freitag soll ein Tier-Steckbrief fertig sein.',
      ],
      choices: <String>[
        'Bis Freitag soll ein Tier-Steckbrief fertig sein.',
        'Bis Freitag soll ein Gedicht auswendig gelernt werden.',
        'Bis morgen muss ein Plakat über Planeten fertig sein.',
      ],
      spokenText:
          'Sucht euch ein heimisches Tier aus. Erstellt dazu einen kurzen Steckbrief mit Lebensraum, Nahrung und zwei Besonderheiten. Bringt den fertigen Steckbrief am Freitag mit.',
    ),
    GermanTask(
      id: 'g3-present-topic',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welcher Einstieg nennt das Thema klar?',
      prompt: 'Hör den Auftrag und wähle einen passenden Anfang.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Heute zeige ich euch, wie ein Regenbogen entsteht.',
      ],
      choices: <String>[
        'Heute zeige ich euch, wie ein Regenbogen entsteht.',
        'Also, ich erzähle jetzt irgendetwas.',
        'Das Wichtigste verrate ich vielleicht später.',
      ],
      spokenText:
          'Du sollst deiner Klasse kurz erklären, wie ein Regenbogen entsteht.',
    ),
    GermanTask(
      id: 'g3-present-three-parts',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Welche Gliederung ist für einen kurzen Vortrag sinnvoll?',
      prompt: 'Hör das Thema und wähle die klare Reihenfolge.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Thema nennen – zwei wichtige Punkte erklären – zusammenfassen',
      ],
      choices: <String>[
        'Thema nennen – zwei wichtige Punkte erklären – zusammenfassen',
        'Mit dem Ende beginnen – Thema wechseln – plötzlich aufhören',
        'Alle Einzelheiten ohne Reihenfolge erzählen',
      ],
      spokenText: 'Du stellst in zwei Minuten dein Lieblingsbuch vor.',
    ),
    GermanTask(
      id: 'g3-present-audience',
      competencyId: GermanCompetencyId.presentationStructure,
      recommendedFromGrade: GradeLevel.third,
      instruction: 'Was macht einen Vortrag verständlich?',
      prompt: 'Hör die Situation und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Ich nenne zuerst das Thema und erkläre dann Schritt für Schritt.',
      ],
      choices: <String>[
        'Ich nenne zuerst das Thema und erkläre dann Schritt für Schritt.',
        'Ich springe ständig zwischen Themen hin und her.',
        'Ich lasse den wichtigsten Punkt weg.',
      ],
      spokenText:
          'Du erklärst deiner Klasse, wie man ein einfaches Papierboot faltet.',
    ),
    GermanTask(
      id: 'g4-discuss-schoolyard',
      competencyId: GermanCompetencyId.discussionReasoning,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Antwort enthält eine begründete Meinung?',
      prompt: 'Hör die Frage und wähle einen passenden Beitrag.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Ich finde mehr Sitzbänke gut, weil dann auch ruhige Pausenplätze entstehen.',
      ],
      choices: <String>[
        'Ich finde mehr Sitzbänke gut, weil dann auch ruhige Pausenplätze entstehen.',
        'Mehr Sitzbänke sind einfach besser.',
        'Meine Meinung ist richtig, weil ich das sage.',
      ],
      spokenText:
          'Die Klasse diskutiert, ob auf dem Schulhof zusätzliche Sitzbänke aufgestellt werden sollen.',
    ),
    GermanTask(
      id: 'g4-discuss-counterargument',
      competencyId: GermanCompetencyId.discussionReasoning,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Widerspruch bleibt sachlich und begründet?',
      prompt: 'Hör die Aussage und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Ich sehe das anders, weil manche Aufgaben gemeinsam leichter zu lösen sind.',
      ],
      choices: <String>[
        'Ich sehe das anders, weil manche Aufgaben gemeinsam leichter zu lösen sind.',
        'Das stimmt überhaupt nicht!',
        'Du hast sowieso keine Ahnung.',
      ],
      spokenText:
          'Ein Kind sagt: Gruppenarbeit sollte es nie geben, weil man allein immer schneller ist.',
    ),
    GermanTask(
      id: 'g4-discuss-build-on',
      competencyId: GermanCompetencyId.discussionReasoning,
      recommendedFromGrade: GradeLevel.fourth,
      instruction:
          'Welche Antwort knüpft sinnvoll an den vorherigen Beitrag an?',
      prompt: 'Hör den Beitrag und wähle eine passende Fortsetzung.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Deine Idee mit den Pflanzen gefällt mir. Zusätzlich könnten wir einen Gießdienst einteilen.',
      ],
      choices: <String>[
        'Deine Idee mit den Pflanzen gefällt mir. Zusätzlich könnten wir einen Gießdienst einteilen.',
        'Ich möchte jetzt lieber über Sport reden.',
        'Ich habe deinen Vorschlag nicht gehört.',
      ],
      spokenText:
          'Ein Mitschüler schlägt vor, mehr Pflanzen im Klassenraum aufzustellen.',
    ),
    GermanTask(
      id: 'g4-direct-speech-call',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satz ist richtig geschrieben?',
      prompt: 'Tom ruft, dass der Bus kommt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tom ruft: „Der Bus kommt!“'],
      choices: <String>[
        'Tom ruft: „Der Bus kommt!“',
        'Tom ruft „Der Bus kommt“!',
        'Tom ruft, „Der Bus kommt!“',
      ],
    ),
    GermanTask(
      id: 'g4-direct-speech-reply',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Zeichensetzung ist richtig?',
      prompt: 'Nora antwortet, dass sie morgen kommt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Nora antwortet: „Ich komme morgen.“'],
      choices: <String>[
        'Nora antwortet: „Ich komme morgen.“',
        'Nora antwortet „Ich komme morgen.“',
        'Nora antwortet, „Ich komme morgen.“',
      ],
    ),
    GermanTask(
      id: 'g4-direct-speech-following-clause',
      competencyId: GermanCompetencyId.directSpeechPunctuation,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satz mit nachgestelltem Begleitsatz ist richtig?',
      prompt: 'Ben sagt, dass er gleich startet.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['„Ich starte gleich“, sagt Ben.'],
      choices: <String>[
        '„Ich starte gleich“, sagt Ben.',
        '„Ich starte gleich.“ sagt Ben.',
        '„Ich starte gleich“ sagt Ben.',
      ],
    ),
  ];
}
