import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanLowerPrimaryTaskCatalog {
  const GermanLowerPrimaryTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-letter-sound-f',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe passt zum Laut?',
      prompt: 'fff',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['F'],
      choices: <String>['F', 'W', 'M'],
    ),
    GermanTask(
      id: 'g1-letter-sound-r',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe passt zum Laut?',
      prompt: 'rrr',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['R'],
      choices: <String>['R', 'L', 'N'],
    ),
    GermanTask(
      id: 'g1-letter-sound-n',
      competencyId: GermanCompetencyId.letterSoundMatch,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe passt zum Laut?',
      prompt: 'nnn',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['N'],
      choices: <String>['N', 'M', 'S'],
    ),
    GermanTask(
      id: 'g1-vowel-i',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe ist ein Selbstlaut?',
      prompt: 'Wähle den Selbstlaut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['I'],
      choices: <String>['P', 'I', 'K'],
    ),
    GermanTask(
      id: 'g1-consonant-k',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe ist ein Mitlaut?',
      prompt: 'Wähle den Mitlaut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['K'],
      choices: <String>['A', 'K', 'U'],
    ),
    GermanTask(
      id: 'g1-vowel-u',
      competencyId: GermanCompetencyId.vowelConsonantRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welcher Buchstabe ist ein Selbstlaut?',
      prompt: 'Wähle den Selbstlaut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['U'],
      choices: <String>['D', 'U', 'F'],
    ),
    GermanTask(
      id: 'g1-alpha-affe-esel',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort kommt im Alphabet zuerst?',
      prompt: 'Esel · Affe · Igel',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Affe'],
      choices: <String>['Esel', 'Affe', 'Igel'],
    ),
    GermanTask(
      id: 'g1-alpha-lampe-rose',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort kommt im Alphabet zuerst?',
      prompt: 'Rose · Lampe · Tasse',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Lampe'],
      choices: <String>['Rose', 'Lampe', 'Tasse'],
    ),
    GermanTask(
      id: 'g1-alpha-baum-sonne',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort kommt im Alphabet zuerst?',
      prompt: 'Sonne · Baum · Wolke',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Baum'],
      choices: <String>['Sonne', 'Baum', 'Wolke'],
    ),
    GermanTask(
      id: 'g1-syllables-rakete',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort hat drei Sprechsilben?',
      prompt: 'Sprich die Wörter langsam.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Rakete'],
      choices: <String>['Rakete', 'Hase', 'Schuh'],
    ),
    GermanTask(
      id: 'g1-syllables-hase',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort hat zwei Sprechsilben?',
      prompt: 'Sprich die Wörter langsam.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hase'],
      choices: <String>['Hase', 'Ball', 'Elefant'],
    ),
    GermanTask(
      id: 'g1-syllables-elefant',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort hat drei Sprechsilben?',
      prompt: 'Sprich die Wörter langsam.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Elefant'],
      choices: <String>['Elefant', 'Tisch', 'Wolke'],
    ),
    GermanTask(
      id: 'g1-build-rose',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'R · o · s · e',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Rose'],
      choices: <String>['Rose', 'Hose', 'Reis'],
    ),
    GermanTask(
      id: 'g1-build-nase',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'N · a · s · e',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Nase'],
      choices: <String>['Nase', 'Hase', 'Nuss'],
    ),
    GermanTask(
      id: 'g1-build-limo',
      competencyId: GermanCompetencyId.wordBuilding,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort entsteht aus diesen Lauten?',
      prompt: 'L · i · m · o',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Limo'],
      choices: <String>['Limo', 'Lama', 'Lied'],
    ),
    GermanTask(
      id: 'g1-read-word-tiger',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort steht hier?',
      prompt: 'Tiger',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Tiger'],
      choices: <String>['Tiger', 'Teller', 'Tinte'],
    ),
    GermanTask(
      id: 'g1-read-word-wolke',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort steht hier?',
      prompt: 'Wolke',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Wolke'],
      choices: <String>['Wolke', 'Wolle', 'Wald'],
    ),
    GermanTask(
      id: 'g1-read-word-hase',
      competencyId: GermanCompetencyId.wordRecognition,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Welches Wort steht hier?',
      prompt: 'Hase',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hase'],
      choices: <String>['Hase', 'Hose', 'Haus'],
    ),
    GermanTask(
      id: 'g1-sentence-understand-lina',
      competencyId: GermanCompetencyId.sentenceComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Wohin fährt Lina?',
      prompt: 'Lina fährt mit dem Rad zum Park.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['zum Park'],
      choices: <String>['zum Park', 'zur Schule', 'zum Zoo'],
    ),
    GermanTask(
      id: 'g1-sentence-understand-tom',
      competencyId: GermanCompetencyId.sentenceComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Was trinkt Tom?',
      prompt: 'Tom trinkt morgens einen Kakao.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['einen Kakao'],
      choices: <String>['einen Kakao', 'Wasser', 'Saft'],
    ),
    GermanTask(
      id: 'g1-sentence-understand-ball',
      competencyId: GermanCompetencyId.sentenceComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Wo liegt der Ball?',
      prompt: 'Der Ball liegt unter dem Tisch.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['unter dem Tisch'],
      choices: <String>['unter dem Tisch', 'auf dem Stuhl', 'im Schrank'],
    ),
    GermanTask(
      id: 'g1-listen-blue-bag',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör genau zu. Welche Farbe hat die Tasche?',
      prompt: 'Tippe auf Lautsprecher und wähle die Farbe.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['blau'],
      choices: <String>['blau', 'gelb', 'rot'],
      spokenText: 'Mara trägt heute eine blaue Tasche.',
    ),
    GermanTask(
      id: 'g1-listen-playground',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör genau zu. Wohin geht Ben?',
      prompt: 'Tippe auf Lautsprecher und wähle den Ort.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['zum Spielplatz'],
      choices: <String>['zum Spielplatz', 'zum Bahnhof', 'zur Bücherei'],
      spokenText:
          'Nach der Schule geht Ben mit seiner Schwester zum Spielplatz.',
    ),
    GermanTask(
      id: 'g1-listen-two-apples',
      competencyId: GermanCompetencyId.listeningComprehension,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Hör genau zu. Wie viele Äpfel nimmt Lea?',
      prompt: 'Tippe auf Lautsprecher und wähle die Anzahl.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['zwei'],
      choices: <String>['zwei', 'drei', 'vier'],
      spokenText: 'Lea legt zwei Äpfel in ihren Korb.',
    ),
    GermanTask(
      id: 'g1-talk-raise-hand',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Was passt zu einem guten Gespräch in der Klasse?',
      prompt: 'Hör die Situation und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Ich melde mich und warte, bis ich dran bin.'],
      choices: <String>[
        'Ich melde mich und warte, bis ich dran bin.',
        'Ich rufe meine Antwort sofort hinein.',
        'Ich rede gleichzeitig mit meinem Nachbarn.',
      ],
      spokenText:
          'Die Lehrerin stellt der Klasse eine Frage. Du kennst die Antwort.',
    ),
    GermanTask(
      id: 'g1-talk-ask-politely',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Wie kannst du freundlich nachfragen?',
      prompt: 'Hör die Situation und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Kannst du das bitte etwas lauter sagen?'],
      choices: <String>[
        'Kannst du das bitte etwas lauter sagen?',
        'Rede endlich richtig!',
        'Ich höre einfach nicht mehr zu.',
      ],
      spokenText:
          'Ein Kind erzählt sehr leise. Du hast den letzten Satz nicht gehört.',
    ),
    GermanTask(
      id: 'g1-talk-take-turns',
      competencyId: GermanCompetencyId.conversationRules,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Was hilft, wenn mehrere Kinder etwas sagen möchten?',
      prompt: 'Hör die Situation und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>['Wir sprechen nacheinander.'],
      choices: <String>[
        'Wir sprechen nacheinander.',
        'Alle sprechen gleichzeitig.',
        'Niemand hört den anderen zu.',
      ],
      spokenText:
          'Drei Kinder möchten gleichzeitig von ihrem Wochenende erzählen.',
    ),
    GermanTask(
      id: 'g1-order-dog-runs',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'schnell · Der Hund · rennt',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Der Hund rennt schnell'],
      choices: <String>['Der Hund', 'rennt', 'schnell'],
    ),
    GermanTask(
      id: 'g1-order-anna-paints',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'ein Bild · Anna · malt',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Anna malt ein Bild'],
      choices: <String>['Anna', 'malt', 'ein Bild'],
    ),
    GermanTask(
      id: 'g1-order-flowers-bloom',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'im Garten · Blumen · blühen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Blumen blühen im Garten'],
      choices: <String>['Blumen', 'blühen', 'im Garten'],
    ),
    GermanTask(
      id: 'g2-noun-article-table',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Artikel passt?',
      prompt: '___ Tisch',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['der'],
      choices: <String>['der', 'die', 'das'],
    ),
    GermanTask(
      id: 'g2-noun-article-door',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Artikel passt?',
      prompt: '___ Tür',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die'],
      choices: <String>['der', 'die', 'das'],
    ),
    GermanTask(
      id: 'g2-noun-article-book',
      competencyId: GermanCompetencyId.nounArticle,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Artikel passt?',
      prompt: '___ Buch',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['das'],
      choices: <String>['der', 'die', 'das'],
    ),
    GermanTask(
      id: 'g2-plural-ball',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Wie lautet die Mehrzahl?',
      prompt: 'der Ball',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Bälle'],
      choices: <String>['die Bälle', 'die Hände', 'die Bücher'],
    ),
    GermanTask(
      id: 'g2-plural-hand',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Wie lautet die Mehrzahl?',
      prompt: 'die Hand',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Hände'],
      choices: <String>['die Hände', 'die Bälle', 'die Bücher'],
    ),
    GermanTask(
      id: 'g2-plural-book',
      competencyId: GermanCompetencyId.singularPlural,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Wie lautet die Mehrzahl?',
      prompt: 'das Buch',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Bücher'],
      choices: <String>['die Bücher', 'die Hände', 'die Bälle'],
    ),
    GermanTask(
      id: 'g2-adjective-bright',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort beschreibt eine Eigenschaft?',
      prompt: 'Die helle Lampe leuchtet.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['helle'],
      choices: <String>['helle', 'Lampe', 'leuchtet'],
    ),
    GermanTask(
      id: 'g2-adjective-soft',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort beschreibt eine Eigenschaft?',
      prompt: 'Das weiche Kissen liegt auf dem Bett.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['weiche'],
      choices: <String>['weiche', 'Kissen', 'liegt'],
    ),
    GermanTask(
      id: 'g2-adjective-cold',
      competencyId: GermanCompetencyId.adjectiveRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort beschreibt eine Eigenschaft?',
      prompt: 'Das kalte Wasser spritzt.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['kalte'],
      choices: <String>['kalte', 'Wasser', 'spritzt'],
    ),
    GermanTask(
      id: 'g2-verb-writes',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort sagt, was jemand tut?',
      prompt: 'Mila schreibt einen Brief.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['schreibt'],
      choices: <String>['Mila', 'schreibt', 'Brief'],
    ),
    GermanTask(
      id: 'g2-verb-swims',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort sagt, was jemand tut?',
      prompt: 'Ben schwimmt im Becken.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['schwimmt'],
      choices: <String>['Ben', 'schwimmt', 'Becken'],
    ),
    GermanTask(
      id: 'g2-verb-laughs',
      competencyId: GermanCompetencyId.verbRecognition,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort sagt, was jemand tut?',
      prompt: 'Lina lacht laut.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['lacht'],
      choices: <String>['Lina', 'lacht', 'laut'],
    ),
    GermanTask(
      id: 'g2-verb-inflect-play-he',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Form passt in den Satz?',
      prompt: 'Er ___ im Garten. · Grundform: spielen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['spielt'],
      choices: <String>['spiele', 'spielt', 'spielen'],
    ),
    GermanTask(
      id: 'g2-verb-inflect-jump-we',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Form passt in den Satz?',
      prompt: 'Wir ___ über die Pfütze. · Grundform: springen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['springen'],
      choices: <String>['springe', 'springt', 'springen'],
    ),
    GermanTask(
      id: 'g2-verb-inflect-paint-you',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Form passt in den Satz?',
      prompt: 'Du ___ ein Bild. · Grundform: malen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['malst'],
      choices: <String>['male', 'malst', 'malt'],
    ),
    GermanTask(
      id: 'g2-punctuation-where',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Satzzeichen gehört ans Ende?',
      prompt: 'Wo ist deine Jacke',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['?'],
      choices: <String>['.', '?', '!'],
    ),
    GermanTask(
      id: 'g2-punctuation-sun',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Satzzeichen gehört ans Ende?',
      prompt: 'Die Sonne scheint heute',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['.'],
      choices: <String>['.', '?', '!'],
    ),
    GermanTask(
      id: 'g2-punctuation-stop',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Satzzeichen gehört ans Ende?',
      prompt: 'Stopp',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['!'],
      choices: <String>['.', '?', '!'],
    ),
    GermanTask(
      id: 'g2-sentence-type-question-name',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Satzart ist das?',
      prompt: 'Wie heißt dein Hund?',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Fragesatz'],
      choices: <String>['Fragesatz', 'Aussagesatz', 'Aufforderungssatz'],
    ),
    GermanTask(
      id: 'g2-sentence-type-statement-rain',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Satzart ist das?',
      prompt: 'Heute regnet es.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Aussagesatz'],
      choices: <String>['Fragesatz', 'Aussagesatz', 'Aufforderungssatz'],
    ),
    GermanTask(
      id: 'g2-sentence-type-command-window',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Satzart ist das?',
      prompt: 'Öffne bitte das Fenster!',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Aufforderungssatz'],
      choices: <String>['Fragesatz', 'Aussagesatz', 'Aufforderungssatz'],
    ),
    GermanTask(
      id: 'g2-word-family-swim',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort gehört zur Wortfamilie von „schwimmen“?',
      prompt: 'schwimmen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Schwimmbad'],
      choices: <String>['Schwimmbad', 'Badetuch', 'Wasserflasche'],
    ),
    GermanTask(
      id: 'g2-word-family-paint',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort gehört zur Wortfamilie von „malen“?',
      prompt: 'malen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Maler'],
      choices: <String>['Maler', 'Pinsel', 'Farbe'],
    ),
    GermanTask(
      id: 'g2-word-family-build',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welches Wort gehört zur Wortfamilie von „bauen“?',
      prompt: 'bauen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Baustelle'],
      choices: <String>['Baustelle', 'Hammer', 'Ziegel'],
    ),
    GermanTask(
      id: 'g2-text-info-zoo',
      competencyId: GermanCompetencyId.textInformation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Lies den Text. Welches Tier sieht Nia zuerst?',
      prompt:
          'Nia besucht den Zoo. Zuerst sieht sie die Giraffen. Danach geht sie zu den Pinguinen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['die Giraffen'],
      choices: <String>['die Giraffen', 'die Pinguine', 'die Löwen'],
    ),
    GermanTask(
      id: 'g2-text-info-bus',
      competencyId: GermanCompetencyId.textInformation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Lies den Text. Wie fährt Amir zur Schule?',
      prompt:
          'Amir verlässt um halb acht das Haus. Zur Schule fährt er mit dem Bus.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['mit dem Bus'],
      choices: <String>['mit dem Bus', 'mit dem Fahrrad', 'zu Fuß'],
    ),
    GermanTask(
      id: 'g2-text-info-cake',
      competencyId: GermanCompetencyId.textInformation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Lies den Text. Wer backt den Kuchen?',
      prompt:
          'Mia deckt den Tisch. Ihr Vater backt einen Kuchen. Danach essen beide zusammen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['ihr Vater'],
      choices: <String>['ihr Vater', 'Mia', 'beide zusammen'],
    ),
    GermanTask(
      id: 'g2-retell-scarf',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Nacherzählung hat die richtige Reihenfolge?',
      prompt: 'Hör die kurze Geschichte an und wähle.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Zuerst sucht Emil, dann fragt er nach, zuletzt findet er den Schal.',
      ],
      choices: <String>[
        'Zuerst sucht Emil, dann fragt er nach, zuletzt findet er den Schal.',
        'Zuerst findet Emil den Schal, dann sucht er, zuletzt fragt er nach.',
        'Zuerst fragt Emil nach, dann findet er den Schal, zuletzt beginnt er zu suchen.',
      ],
      spokenText:
          'Emil vermisst seinen Schal. Er sucht in der Garderobe und fragt danach seine Lehrerin. Schließlich entdeckt er den Schal unter seiner Bank.',
    ),
    GermanTask(
      id: 'g2-retell-seed',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welche Nacherzählung enthält das Wichtigste?',
      prompt: 'Hör zu und wähle die passende Kurzfassung.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Lina pflanzt einen Samen, gießt ihn und später wächst eine kleine Pflanze.',
      ],
      choices: <String>[
        'Lina pflanzt einen Samen, gießt ihn und später wächst eine kleine Pflanze.',
        'Lina hat einen grünen Becher und das Fenster ist offen.',
        'Lina sitzt am Tisch und schaut aus dem Fenster.',
      ],
      spokenText:
          'Lina legt einen Samen in einen Topf mit Erde. Jeden Tag gießt sie ihn ein wenig. Nach einigen Tagen wächst eine kleine grüne Pflanze.',
    ),
    GermanTask(
      id: 'g2-retell-bike',
      competencyId: GermanCompetencyId.oralRetelling,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Welcher Satz passt als Schluss der Nacherzählung?',
      prompt: 'Hör die Geschichte und wähle den passenden Schluss.',
      interaction: GermanTaskInteraction.listeningChoice,
      acceptedAnswers: <String>[
        'Am Ende kann Leo wieder mit dem Fahrrad fahren.',
      ],
      choices: <String>[
        'Am Ende kann Leo wieder mit dem Fahrrad fahren.',
        'Am Ende kauft Leo einen neuen Fußball.',
        'Am Ende beginnt die Schule von vorn.',
      ],
      spokenText:
          'Leos Fahrrad hat einen platten Reifen. Gemeinsam mit seiner Mutter flickt er den Schlauch. Danach pumpt Leo den Reifen wieder auf und fährt eine Runde.',
    ),
    GermanTask(
      id: 'g2-write-sentence-dog',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'der Hund · schläft · im Korb',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Der Hund schläft im Korb.',
        'Im Korb schläft der Hund.',
      ],
    ),
    GermanTask(
      id: 'g2-write-sentence-book',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'Mia · liest · ein Buch',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>['Mia liest ein Buch.', 'Ein Buch liest Mia.'],
    ),
    GermanTask(
      id: 'g2-write-sentence-playground',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'die Kinder · spielen · auf dem Hof',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Die Kinder spielen auf dem Hof.',
        'Auf dem Hof spielen die Kinder.',
      ],
    ),
  ];
}
