import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGradeFourExtensionTaskCatalog {
  const GermanGradeFourExtensionTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g4-compound-bike-workshop',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Bedeutung hat das zusammengesetzte Wort?',
      prompt: 'Fahrradwerkstatt',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Werkstatt für Fahrräder'],
      choices: <String>[
        'Werkstatt für Fahrräder',
        'Werkstatt aus Fahrrädern',
        'Fahrrad für eine Werkstatt',
      ],
    ),
    GermanTask(
      id: 'g4-compound-rain-water-tank',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Aus welchen Wörtern ist das Nomen aufgebaut?',
      prompt: 'Regenwasserbehälter',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Regen + Wasser + Behälter'],
      choices: <String>[
        'Regen + Wasser + Behälter',
        'Regen + Waschen + Behälter',
        'Regel + Wasser + Behälter',
      ],
    ),
    GermanTask(
      id: 'g4-compound-children-book-author',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Erklärung passt zum Wort?',
      prompt: 'Kinderbuchautor',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Autor von Kinderbüchern'],
      choices: <String>[
        'Autor von Kinderbüchern',
        'Kind eines Buchautors',
        'Buch über einen Autor',
      ],
    ),
    GermanTask(
      id: 'g4-compound-school-library-card',
      competencyId: GermanCompetencyId.compoundWords,
      recommendedFromGrade: GradeLevel.fourth,
      instruction:
          'Welcher Wortteil sagt, was der Gegenstand hauptsächlich ist?',
      prompt: 'Schulbibliotheksausweis',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Ausweis'],
      choices: <String>['Ausweis', 'Schule', 'Bibliothek'],
    ),
    GermanTask(
      id: 'g4-predicate-separable-rest',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was ist das vollständige Prädikat?',
      prompt: 'Nach dem Training ruhen sich die Spieler aus.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['ruhen sich aus'],
      choices: <String>['ruhen sich aus', 'die Spieler', 'Nach dem Training'],
    ),
    GermanTask(
      id: 'g4-predicate-separable-prepare',
      competencyId: GermanCompetencyId.subjectPredicate,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was ist das vollständige Prädikat?',
      prompt: 'Morgen bereitet die Klasse das Fest vor.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['bereitet vor'],
      choices: <String>['bereitet vor', 'die Klasse', 'das Fest'],
    ),
    GermanTask(
      id: 'g4-constituent-means-train',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satzteil antwortet auf „Womit?“',
      prompt: 'Am Freitag fährt unsere Klasse mit dem Zug nach Weimar.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['mit dem Zug'],
      choices: <String>['mit dem Zug', 'Am Freitag', 'nach Weimar'],
    ),
    GermanTask(
      id: 'g4-constituent-reason-rain',
      competencyId: GermanCompetencyId.sentenceConstituents,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welcher Satzteil antwortet auf „Warum?“',
      prompt: 'Wegen des starken Regens bleibt die Pause heute drinnen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Wegen des starken Regens'],
      choices: <String>[
        'Wegen des starken Regens',
        'die Pause',
        'heute drinnen',
      ],
    ),
    GermanTask(
      id: 'g4-tense-perfect-read',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Form passt ins Perfekt?',
      prompt: 'Heute liest Mia das Buch. Gestern hat Mia das Buch ___.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['gelesen'],
      choices: <String>['gelesen', 'las', 'liest'],
    ),
    GermanTask(
      id: 'g4-tense-future-plan',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Verbform drückt Zukunft aus?',
      prompt: 'Nächste Woche ___ wir das Museum besuchen.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['werden'],
      choices: <String>['werden', 'wurden', 'sind'],
    ),
    GermanTask(
      id: 'g4-word-family-read',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Wörter gehören sicher zur selben Wortfamilie?',
      prompt: 'Achte auf den gemeinsamen Wortstamm.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['lesen · Leser · lesbar'],
      choices: <String>[
        'lesen · Leser · lesbar',
        'lesen · leise · Leser',
        'Leser · lösen · lesbar',
      ],
    ),
    GermanTask(
      id: 'g4-word-family-drive',
      competencyId: GermanCompetencyId.wordFamilies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Wörter gehören zur Wortfamilie „fahr-“?',
      prompt: 'Finde die drei verwandten Wörter.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['fahren · Fahrer · Fahrt'],
      choices: <String>[
        'fahren · Fahrer · Fahrt',
        'fahren · Farbe · Fahrt',
        'Fahrer · Falle · Fahrt',
      ],
    ),
    GermanTask(
      id: 'g4-inference-wet-dog',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Was kann man aus den Hinweisen schließen?',
      prompt:
          'Als Nia in die Küche kommt, steht das Fenster offen. Auf dem Boden sind nasse Pfotenabdrücke. Der Hund schüttelt sein Fell.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Der Hund kam wahrscheinlich gerade aus dem Regen.',
      ],
      choices: <String>[
        'Der Hund kam wahrscheinlich gerade aus dem Regen.',
        'Nia hat den Boden mit Absicht nass gemacht.',
        'Der Hund hat den ganzen Tag geschlafen.',
      ],
    ),
    GermanTask(
      id: 'g4-inference-early-alarm',
      competencyId: GermanCompetencyId.readingInference,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Schlussfolgerung passt am besten?',
      prompt:
          'Paul legt am Abend seine Sportsachen neben die Tür und stellt den Wecker eine Stunde früher als sonst.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>[
        'Paul hat am nächsten Morgen wahrscheinlich früh Sport.',
      ],
      choices: <String>[
        'Paul hat am nächsten Morgen wahrscheinlich früh Sport.',
        'Paul möchte seine Sportsachen wegwerfen.',
        'Paul hat den Wecker versehentlich verstellt.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-plant',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Reihenfolge ergibt einen sinnvollen Ablauf?',
      prompt:
          '1 Erde in den Topf füllen · 2 Samen einsetzen · 3 vorsichtig gießen · 4 Topf ans Licht stellen',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['1 – 2 – 3 – 4'],
      choices: <String>['1 – 2 – 3 – 4', '3 – 1 – 4 – 2', '4 – 2 – 1 – 3'],
    ),
    GermanTask(
      id: 'g4-sequence-library',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welche Reihenfolge passt zu einer Büchereiausleihe?',
      prompt:
          'A Buch auswählen · B im Katalog suchen · C mit Ausweis ausleihen · D Regalnummer finden',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['B – D – A – C'],
      choices: <String>['B – D – A – C', 'C – A – D – B', 'A – C – B – D'],
    ),
    GermanTask(
      id: 'g4-spelling-extension-hand',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Welches verwandte Wort hilft dir beim letzten Laut?',
      prompt: 'Han_',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Hände'],
      choices: <String>['Hände', 'Hahn', 'Handy'],
    ),
    GermanTask(
      id: 'g4-dictionary-guide-schmetterling',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Zwischen welchen Leitwörtern findest du „Schmetterling“?',
      prompt: 'Vergleiche die Wörter alphabetisch.',
      interaction: GermanTaskInteraction.singleChoice,
      acceptedAnswers: <String>['Schlange – Schule'],
      choices: <String>[
        'Schlange – Schule',
        'Schule – See',
        'Regen – Schlange',
      ],
    ),
  ];
}
