import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanGradeFourDiversityTaskCatalog {
  const GermanGradeFourDiversityTaskCatalog._();

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g4-spell-korb-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Körbe“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Korb'],
      choices: <String>['Kor', 'b', 'p'],
    ),
    GermanTask(
      id: 'g4-spell-dieb-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Diebe“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Dieb'],
      choices: <String>['Die', 'b', 'p'],
    ),
    GermanTask(
      id: 'g4-spell-weg-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Wege“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Weg'],
      choices: <String>['We', 'g', 'k'],
    ),
    GermanTask(
      id: 'g4-spell-kleid-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Kleider“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kleid'],
      choices: <String>['Klei', 'd', 't'],
    ),
    GermanTask(
      id: 'g4-spell-zwerg-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Zwerge“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Zwerg'],
      choices: <String>['Zwer', 'g', 'k'],
    ),
    GermanTask(
      id: 'g4-spell-lob-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „loben“ zum Prüfen und baue das Nomen.',
      prompt: 'das …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Lob'],
      choices: <String>['Lo', 'b', 'p'],
    ),
    GermanTask(
      id: 'g4-spell-haus-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Häuser“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Haus'],
      choices: <String>['Hau', 's', 'ß'],
    ),
    GermanTask(
      id: 'g4-spell-traum-build',
      competencyId: GermanCompetencyId.spellingStrategies,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Nutze „Träume“ zum Prüfen und baue die Einzahl.',
      prompt: 'ein …',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Traum'],
      choices: <String>['Trau', 'm', 'mm'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-schale',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Schaufel · Schalter · Schanze · Schale',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Schale Schalter Schanze Schaufel'],
      choices: <String>['Schaufel', 'Schalter', 'Schanze', 'Schale'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-kle',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Klettern · Kleid · Kleben · Klein',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Kleben Kleid Klein Klettern'],
      choices: <String>['Klettern', 'Kleid', 'Kleben', 'Klein'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-bo',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Bombe · Bohne · Bogen · Boden',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Boden Bogen Bohne Bombe'],
      choices: <String>['Bombe', 'Bohne', 'Bogen', 'Boden'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-fra',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'frei · Frau · Frage · Frack',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Frack Frage Frau frei'],
      choices: <String>['frei', 'Frau', 'Frage', 'Frack'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-schl',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Schloss · schlimm · Schleife · Schlange',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Schlange Schleife schlimm Schloss'],
      choices: <String>['Schloss', 'schlimm', 'Schleife', 'Schlange'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-krabbe',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Krater · krank · Kraft · Krabbe',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Krabbe Kraft krank Krater'],
      choices: <String>['Krater', 'krank', 'Kraft', 'Krabbe'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-spa',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Specht · Spatz · sparen · spannen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['spannen sparen Spatz Specht'],
      choices: <String>['Specht', 'Spatz', 'sparen', 'spannen'],
    ),
    GermanTask(
      id: 'g4-dictionary-order-bla-ble',
      competencyId: GermanCompetencyId.dictionarySkills,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Wörter wie im Wörterbuch.',
      prompt: 'Blech · blau · Blatt · Blase',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Blase Blatt blau Blech'],
      choices: <String>['Blech', 'blau', 'Blatt', 'Blase'],
    ),
    GermanTask(
      id: 'g4-tense-go-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Mia ist nach Hause ___. · Grundform: gehen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gegangen'],
      choices: <String>['ge', 'gang', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-see-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Ben hat den Film ___. · Grundform: sehen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gesehen'],
      choices: <String>['ge', 'seh', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-find-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Lea hat den Schlüssel ___. · Grundform: finden',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gefunden'],
      choices: <String>['ge', 'fund', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-come-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Der Bus ist pünktlich ___. · Grundform: kommen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gekommen'],
      choices: <String>['ge', 'komm', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-write-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Tom hat einen Bericht ___. · Grundform: schreiben',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['geschrieben'],
      choices: <String>['ge', 'schrieb', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-drink-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Nora hat Wasser ___. · Grundform: trinken',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['getrunken'],
      choices: <String>['ge', 'trunk', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-read-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Mia hat das Buch ___. · Grundform: lesen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gelesen'],
      choices: <String>['ge', 'les', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-tense-drive-perfect-build',
      competencyId: GermanCompetencyId.verbTenses,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Baue das Partizip für das Perfekt.',
      prompt: 'Opa ist nach Erfurt ___. · Grundform: fahren',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['gefahren'],
      choices: <String>['ge', 'fahr', 'en', 't'],
    ),
    GermanTask(
      id: 'g4-sequence-poster-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Sachplakat erstellen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema klären. Informationen auswählen. Entwurf skizzieren. Plakat gestalten.',
      ],
      choices: <String>[
        'Plakat gestalten.',
        'Informationen auswählen.',
        'Thema klären.',
        'Entwurf skizzieren.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-protocol-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Versuchsprotokoll schreiben',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Fragestellung notieren. Material aufschreiben. Durchführung beschreiben. Ergebnis festhalten.',
      ],
      choices: <String>[
        'Ergebnis festhalten.',
        'Material aufschreiben.',
        'Fragestellung notieren.',
        'Durchführung beschreiben.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-book-talk-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Vorbereitungsschritte sinnvoll.',
      prompt: 'Eine Buchvorstellung vorbereiten',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Buch auswählen. Wichtige Notizen sammeln. Lesestelle festlegen. Vorstellung üben.',
      ],
      choices: <String>[
        'Vorstellung üben.',
        'Lesestelle festlegen.',
        'Buch auswählen.',
        'Wichtige Notizen sammeln.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-route-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Planungsschritte sinnvoll.',
      prompt: 'Einen Ausflugsweg planen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Ziel festlegen. Karte prüfen. Weg auswählen. Zeiten notieren.',
      ],
      choices: <String>[
        'Zeiten notieren.',
        'Weg auswählen.',
        'Ziel festlegen.',
        'Karte prüfen.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-plant-test-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Pflanzenexperiment planen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Frage festlegen. Töpfe beschriften. Bedingungen verändern. Beobachtungen notieren.',
      ],
      choices: <String>[
        'Beobachtungen notieren.',
        'Bedingungen verändern.',
        'Frage festlegen.',
        'Töpfe beschriften.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-interview-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Interview durchführen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Thema festlegen. Fragen vorbereiten. Interview führen. Antworten zusammenfassen.',
      ],
      choices: <String>[
        'Interview führen.',
        'Antworten zusammenfassen.',
        'Fragen vorbereiten.',
        'Thema festlegen.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-newspaper-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Eine Klassenzeitung erstellen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Themen sammeln. Aufgaben verteilen. Beiträge schreiben. Texte gemeinsam prüfen.',
      ],
      choices: <String>[
        'Texte gemeinsam prüfen.',
        'Themen sammeln.',
        'Beiträge schreiben.',
        'Aufgaben verteilen.',
      ],
    ),
    GermanTask(
      id: 'g4-sequence-chart-order',
      competencyId: GermanCompetencyId.textSequence,
      recommendedFromGrade: GradeLevel.fourth,
      instruction: 'Ordne die Arbeitsschritte sinnvoll.',
      prompt: 'Ein Diagramm aus Daten erstellen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>[
        'Daten sammeln. Werte ordnen. Diagramm zeichnen. Titel und Beschriftung ergänzen.',
      ],
      choices: <String>[
        'Diagramm zeichnen.',
        'Daten sammeln.',
        'Titel und Beschriftung ergänzen.',
        'Werte ordnen.',
      ],
    ),
  ];
}
