import '../../core/grade_level.dart';
import 'german_competency.dart';
import 'german_task.dart';

class GermanLowerPrimaryDepthTaskCatalog {
  const GermanLowerPrimaryDepthTaskCatalog._();

  static const _sentenceTypeChoices = <String>[
    'Fragesatz',
    'Aussagesatz',
    'Aufforderungssatz',
    '?',
    '.',
    '!',
  ];

  static const tasks = <GermanTask>[
    GermanTask(
      id: 'g1-alpha-order-transport-depth',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Zug · Fahrrad · Bus · Auto',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Auto Bus Fahrrad Zug'],
      choices: <String>['Zug', 'Fahrrad', 'Bus', 'Auto'],
    ),
    GermanTask(
      id: 'g1-alpha-order-clothes-depth',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Schal · Hose · Mütze · Jacke',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Hose Jacke Mütze Schal'],
      choices: <String>['Schal', 'Hose', 'Mütze', 'Jacke'],
    ),
    GermanTask(
      id: 'g1-alpha-order-room-depth',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Tisch · Regal · Bett · Lampe',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Bett Lampe Regal Tisch'],
      choices: <String>['Tisch', 'Regal', 'Bett', 'Lampe'],
    ),
    GermanTask(
      id: 'g1-alpha-order-body-depth',
      competencyId: GermanCompetencyId.alphabeticalOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Ordne die Wörter alphabetisch.',
      prompt: 'Nase · Hand · Bein · Arm',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Arm Bein Hand Nase'],
      choices: <String>['Nase', 'Hand', 'Bein', 'Arm'],
    ),
    GermanTask(
      id: 'g1-syllable-build-ananas-depth',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Ananas',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Ananas'],
      choices: <String>['A', 'na', 'nas', 'nis'],
    ),
    GermanTask(
      id: 'g1-syllable-build-schokolade-depth',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Schokolade',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Schokolade'],
      choices: <String>['Scho', 'ko', 'la', 'de', 'do'],
    ),
    GermanTask(
      id: 'g1-syllable-build-giraffe-depth',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Giraffe',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Giraffe'],
      choices: <String>['Gi', 'raf', 'fe', 'fo'],
    ),
    GermanTask(
      id: 'g1-syllable-build-kamera-depth',
      competencyId: GermanCompetencyId.syllableSegmentation,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Sprich das Wort langsam und baue es aus Sprechsilben.',
      prompt: 'Kamera',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['Kamera'],
      choices: <String>['Ka', 'me', 'ra', 'ro'],
    ),
    GermanTask(
      id: 'g1-order-cat-sleeps-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'ruhig · Die Katze · schläft',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Die Katze schläft ruhig'],
      choices: <String>['ruhig', 'Die Katze', 'schläft'],
    ),
    GermanTask(
      id: 'g1-order-ben-door-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'die Tür · Ben · öffnet',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Ben öffnet die Tür'],
      choices: <String>['die Tür', 'Ben', 'öffnet'],
    ),
    GermanTask(
      id: 'g1-order-mia-star-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'einen Stern · malt · Mia',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Mia malt einen Stern'],
      choices: <String>['einen Stern', 'malt', 'Mia'],
    ),
    GermanTask(
      id: 'g1-order-bus-punctual-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'pünktlich · Der Bus · kommt',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Der Bus kommt pünktlich'],
      choices: <String>['pünktlich', 'Der Bus', 'kommt'],
    ),
    GermanTask(
      id: 'g1-order-we-play-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'im Hof · Wir · spielen',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Wir spielen im Hof'],
      choices: <String>['im Hof', 'Wir', 'spielen'],
    ),
    GermanTask(
      id: 'g1-order-grandpa-paper-depth',
      competencyId: GermanCompetencyId.sentenceWordOrder,
      recommendedFromGrade: GradeLevel.first,
      instruction: 'Bringe die Wörter in die richtige Reihenfolge.',
      prompt: 'die Zeitung · liest · Opa',
      interaction: GermanTaskInteraction.wordOrder,
      acceptedAnswers: <String>['Opa liest die Zeitung'],
      choices: <String>['die Zeitung', 'liest', 'Opa'],
    ),
    GermanTask(
      id: 'g2-inflect-live-you-depth',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Du ___ in Erfurt. · Grundform: wohnen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['wohnst'],
      choices: <String>['wohn', 'st', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-ask-he-depth',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Er ___ nach dem Weg. · Grundform: fragen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['fragt'],
      choices: <String>['frag', 't', 'en'],
    ),
    GermanTask(
      id: 'g2-inflect-cook-we-depth',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Wir ___ eine Suppe. · Grundform: kochen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['kochen'],
      choices: <String>['koch', 'en', 't'],
    ),
    GermanTask(
      id: 'g2-inflect-gym-you-plural-depth',
      competencyId: GermanCompetencyId.verbInflection,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Baue die passende Verbform.',
      prompt: 'Ihr ___ in der Halle. · Grundform: turnen',
      interaction: GermanTaskInteraction.wordBuilder,
      acceptedAnswers: <String>['turnt'],
      choices: <String>['turn', 't', 'en'],
    ),
    GermanTask(
      id: 'g2-punctuation-film-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Wann beginnt der Film',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-cat-sofa-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Die Katze schläft auf dem Sofa',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-place-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Räum bitte deinen Platz auf',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-friend-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Wo wohnt dein Freund',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-grandma-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Morgen besuchen wir Oma',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-punctuation-stop-depth',
      competencyId: GermanCompetencyId.sentencePunctuation,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Bleib bitte stehen',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-sky-depth',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Warum ist der Himmel blau',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-bus-depth',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Der Bus hält vor der Schule',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-name-depth',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Schreib deinen Namen auf',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aufforderungssatz', '!'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-come-later-depth',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Kommst du nachher mit',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Fragesatz', '?'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-type-three-o-clock-depth',
      competencyId: GermanCompetencyId.sentenceTypes,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Markiere Satzart und passendes Satzzeichen.',
      prompt: 'Wir treffen uns um drei Uhr',
      interaction: GermanTaskInteraction.tokenSelection,
      acceptedAnswers: <String>['Aussagesatz', '.'],
      choices: _sentenceTypeChoices,
    ),
    GermanTask(
      id: 'g2-write-bird-roof-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'der Vogel · sitzt · auf dem Dach',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Der Vogel sitzt auf dem Dach.',
        'Auf dem Dach sitzt der Vogel.',
      ],
    ),
    GermanTask(
      id: 'g2-write-morning-school-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'am Morgen · fährt Lea · zur Schule',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Am Morgen fährt Lea zur Schule.',
        'Lea fährt am Morgen zur Schule.',
      ],
    ),
    GermanTask(
      id: 'g2-write-tom-book-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'Tom · liest · ein Buch',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>['Tom liest ein Buch.'],
    ),
    GermanTask(
      id: 'g2-write-garden-tulips-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'im Garten · blühen · rote Tulpen',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Im Garten blühen rote Tulpen.',
        'Rote Tulpen blühen im Garten.',
      ],
    ),
    GermanTask(
      id: 'g2-write-tower-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'wir · bauen · einen Turm',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>['Wir bauen einen Turm.'],
    ),
    GermanTask(
      id: 'g2-write-afternoon-football-depth',
      competencyId: GermanCompetencyId.sentenceWriting,
      recommendedFromGrade: GradeLevel.second,
      instruction: 'Schreibe aus den Wörtern einen vollständigen Satz.',
      prompt: 'nachmittags · spielt Ben · Fußball',
      interaction: GermanTaskInteraction.typedText,
      acceptedAnswers: <String>[
        'Nachmittags spielt Ben Fußball.',
        'Ben spielt nachmittags Fußball.',
      ],
    ),
  ];
}
